/* MASAL 03 — ASLAN İLE FARE (Ezop)
   ─────────────────────────────────
   NEDEN AÇILABİLİYOR: Fablın iki yarısı var ve ikisi de iş dolu.
   Birinci yarıda fareler otlakta yaşar, aslanı uyandırır, bağışlanır.
   İkinci yarıda aslan avcıların ağına düşer ve bütün fare kolonisi
   onu kurtarmak için örgütlenir. Kurtarma operasyonu tek başına bir
   ders saatidir: gözcülük, ip, su, ağın kesilmesi.

   FİNALİ YUMUŞATTIM: Ezop'ta aslan fareyi yakalayıp yemekle tehdit eder.
   Burada aslan huysuzdur, kükrer, sonra utanır ve bırakır. Korku yok;
   "büyük olan da özür diler" var. Avcılar da görünmez — yalnızca
   bıraktıkları ağ vardır, kimse kovalanmaz.

   MERKEZ TERSİNE ÇALIŞIR: Ambar dolmuyor, AĞ ÇÖZÜLÜYOR. Sınıf
   ilerledikçe aslanın üstündeki ipler teker teker kayboluyor. */

export default {
  kod: 'aslan',
  ad: 'Aslan ile Fare',
  kaynak: 'Ezop fablı',
  ders: 'En küçük dost, en büyük yardımı yapabilir',
  sure: '40 dakika · bütün sınıf',
  ozet: 'Otlakta bir fare kocaman bir aslanla dost olur; aslan ağa düşünce bütün koloni onu kurtarmaya gider.',
  renk: '#D8A34F',
  ikon: 'aslan-kosele',

  /* KURGU: kurtarma. Armağan toplama yok — tek hedef var ve engel geri
     sayıyor. Sınıf bir şey biriktirmiyor, bir şeyi söküyor. */
  kurgu: 'kurtarma',
  kurtarma: { hedef: { kod: 'aslan-kosele', ad: 'Kösele' }, dugum: 12, dugumIkon: 'kazik2' },

  /* Mekân: savan. Ortada aslanın kayası; ilerledikçe ağ çözülüyor. */
  dunya: { mekan: 'savan', gok: 0xf2e6cc, cevre: 0xd9c98a, cekirdek: 77113,
    piyonTur: 'fare', piyon: 0xa88a6c, piyonKarin: 0xf0e2cc, piyonIc: 0xeba79c,   // çocuk bir fare olarak dolaşır
    /* Çözülen her durak kayanın çevresine bir fare daha getirir — sınıf
       ilerledikçe koloni gözle görülür biçimde toplanıyor. */
    izNotu: { bos: 'Koloni henüz toplanmadı', dolu: '{n} fare geldi · ağ çözülüyor' },
    iz: 'fare', izRenk: 0xd9cdb6, kesifRenk: 0xd8a34f,
    kesif: [
      { x: -9.6, z: -6.8, ikon: 'yaprak', ad: 'Akasya',
        metin: 'Savanın şemsiyesi. Öğlen sıcağında bütün otlak bu ağacın gölgesine sığar — aslanı da, fareleri de. Kimse kimseye karışmaz.' },
      { x: 0, z: 3.6, ikon: 'tas', ad: 'Kösele’nin kayası',
        metin: 'Kösele her gün öğleden sonra buraya çıkıp uyur. Kaya güneşten ısınır, akşama kadar sıcak kalır. Fareler o yüzden kayanın dibinde ısınır.' },
      { x: 7.4, z: 4.2, ikon: 'su', ad: 'Nehir',
        metin: 'Otlakta su yalnızca burada var. Sabah aslan, öğlen antiloplar, akşam fareler iner. Sıra hiç konuşulmadan, kendiliğinden oluşmuş.' },
      { x: -10.6, z: -2.4, ikon: 'yuva', ad: 'Fare yuvaları',
        metin: 'Toprağın altında birbirine bağlı onlarca oda var. Toz bu yolların tamamını ezbere bilir; kolonide haritayı aklında tutan tek kişi o.' },
      { x: 12.8, z: -9.7, ikon: 'kartal', ad: 'Gözcü kayalığı',
        metin: 'Kanat gününün çoğunu burada geçirir. Buradan ovanın en ucu bile görünür — tehlikeyi otlaktan önce burası fark eder.' }
    ]},

  acilis: [
    { tag: 'BİR VARMIŞ, BİR YOKMUŞ', baslik: 'Otlakta minik bir koloni.', ikon: 'toprak',
      metin: 'Uçsuz bucaksız bir otlakta, sarı otların altında bir fare kolonisi yaşarmış. Küçüktüler, hızlıydılar ve birbirlerini hiç yalnız bırakmazlardı. En küçükleri Fındık’tı; en meraklıları da o.' },
    { tag: 'UYUYAN DEV', baslik: 'Kayanın üstünde bir aslan.', ikon: 'tas',
      metin: 'Otlağın ortasındaki büyük kayanın üstünde Kösele adında bir aslan uyurdu. Kocamandı, sesi gök gürültüsü gibiydi ve uyandırılmaktan hiç hoşlanmazdı. Fareler o kayadan uzak dururdu — Fındık hariç.' },
    { tag: 'BU MASALIN KAHRAMANI SİZSİNİZ', baslik: 'Küçük olmak zayıf olmak değil.', ikon: 'kalp',
      metin: 'Bugün sırayla tahtaya gelip önce bir dostluk kuracağız, sonra o dostluğun ne işe yaradığını göreceğiz. Çünkü kocaman bir aslanın bile bir gün minik bir fareye ihtiyacı olabilir.' }
  ],

  bolumler: [
    {
      kod: 'otlak', asamaSonu: 'Dostluk kuruldu — artık yalnız değil', ad: 'Otlak', baslik: 'Dostluk kurulur',
      renk: '#D2B35C', acik: '#F5E7B8', gok: '#FBF2D9', zemin: '#DDC87C',
      hikaye: 'Sarı otların arasında koloninin günlük işi var: erzak toplanacak, yuvalar onarılacak, yollar açılacak. Ve Fındık, tam da kayanın üstüne tırmanmış, Kösele’nin burnunda zıplıyor.',
      soz: '“Meraklı olmak yaramazlık değildir; sadece dikkat ister.”',
      karakter: { kod: 'fare-findik', ad: 'Fındık', tur: 'Meraklı fare' },
      sozler: [ 'Ben Fındık! Korkmuyorum, sadece merak ediyorum.', 'Bak, birlikte çok iyi gidiyoruz!', 'Kösele bana kızmadı — hatta gülümsedi!' ],
      armagan: { kod: 'tohum', ad: 'Buğday tanesi', renk: '#BD8451' },
      engeller: [
        { engel: 'Rüzgâr koloninin erzağını savuruyor.',
          sahne: { tip: 'sorun', nesne: 'tohum', adet: 6, kisi: 'fare-findik', dekor: ['ot','saman','basak'],
            metin: 'Otlakta sıcak bir rüzgâr esti. Koloninin topladığı buğday taneleri havalandı, dört bir yana savruldu.', soz: 'Tanelerimiz uçuyor!' }, gorev: 'yakala',
          yonerge: 'Rüzgâr taneleri savuruyor. Parmağını aşağıda gezdir, sepeti kaydır ve düşenleri tut.',
          hedef: 8, hiz: .18, sikayet: 1150, iyi: [ 'tohum', 'ot' ], kotu: [],
          cozum: 'Taneler sepette; rüzgâra bir tane bile kaptırmadık.' },
        { engel: 'Yuvaya taşınacaklar karışmış.',
          sahne: { tip: 'kesif', nesne: 'saman', adet: 4, kisi: 'fare-findik', dekor: ['ot','tas','saman'],
            metin: 'Fındık yuvanın kapısına bir yığın getirdi: buğday, kuru ot, yaprak… Ama aralarına taş, şişe, hatta bir ayakkabı karışmış.', soz: 'Bunların hepsi içeri sığmaz ki!' }, gorev: 'ayir',
          yonerge: 'Hangisi yuvaya girer, hangisi girmez? Birlikte ayıralım.',
          kutular: ['Yuvaya girer', 'Dışarıda kalır'],
          ogeler: [ { ad: 'Buğday', sekil: 'tohum', dogru: 0 }, { ad: 'Kuru ot', sekil: 'ot', dogru: 0 },
                    { ad: 'Yaprak', sekil: 'yaprak', dogru: 0 }, { ad: 'Koca taş', sekil: 'tas', dogru: 1 },
                    { ad: 'Şişe', sekil: 'sise', dogru: 1 }, { ad: 'Ayakkabı', sekil: 'ayakkabi', dogru: 1 } ],
          cozum: 'Yuva düzenlendi; her şey yerli yerinde.' },
        { engel: 'Otların arasında koloni dostları kaybolmuş.',
          sahne: { tip: 'kesif', nesne: 'ot', adet: 6, kisi: 'fare-findik', dekor: ['ot','saman','ot'],
            metin: 'Sarı otlar Fındık’ın boyunu geçmiş. Dostları saklambaç oynarken otların arasına dalmış; şimdi hiçbiri görünmüyor.', soz: 'Neredesiniz? Sizi bulacağım!' }, gorev: 'gizli',
          yonerge: 'Sarı otlara iyi bakalım — saklanan dostları bulalım.',
          tohum: 31, sus: 26, susBoy: [4, 8], boy: 12,
          gizli: [ { sekil: 'sincap', ad: 'Sincap', x: 20, y: 62, a: -8 },
                   { sekil: 'kaplumbaga', ad: 'Kaplumbağa', x: 76, y: 30, a: 7 },
                   { sekil: 'kus', ad: 'Kuş', x: 47, y: 75, a: 13 } ],
          cozum: 'Üçü de bulundu; koloni tamam.' },
        { engel: 'Kayaya çıkan yol dikenli.',
          sahne: { tip: 'gelis', nesne: 'kozalak', adet: 4, kisi: 'fare-findik', dekor: ['ot','tas','saman'],
            metin: 'Fındık büyük kayanın tepesini çok merak ediyor. Ama kayaya çıkan yolda dikenli çalılar var; dikkatli yürümek gerek.', soz: 'Tepede ne var acaba?' }, gorev: 'yol',
          yonerge: 'Dikenlere değmeden Fındık’ı kayanın tepesine götürelim.',
          baslangic: { x: 105, y: 220, sekil: 'fare-findik', ad: 'Fındık' },
          bitis: { x: 900, y: 220, sekil: 'tas', ad: 'Büyük kaya' },
          engeller: [ { x: 400, y: 130, r: 88, sekil: 'kozalak', ad: 'Diken' },
                      { x: 620, y: 320, r: 88, sekil: 'kozalak', ad: 'Diken' } ],
          cozum: 'Fındık kayanın tepesine çıktı — ve Kösele’nin burnunu gördü.' },
        { engel: 'Erzak bütün koloniye eşit dağıtılacak.',
          sahne: { tip: 'istek', nesne: 'tohum', adet: 6, kisi: 'fare-findik', dekor: ['ot','saman','basak'],
            metin: 'Toplanan buğday bir yığın oldu. Kolonide üç yuva var; birine çok, birine az giderse birinin karnı guruldar.', soz: 'Herkese eşit düşsün.' }, gorev: 'paylas',
          yonerge: 'Üç yuvaya eşit pay düşsün; kimse aç kalmasın.',
          dostlar: [ { sekil: 'yuva', ad: 'Kuzey yuva' }, { sekil: 'yuva', ad: 'Orta yuva' }, { sekil: 'yuva', ad: 'Güney yuva' } ],
          yem: 'tohum', yemAd: 'Buğday', adet: 9,
          cozum: 'Üç yuva da eşit pay aldı.' },
        { engel: 'Kösele uyandı ve kükredi. Sesi tanımak gerek.',
          sahne: { tip: 'sorun', nesne: 'yildiz', adet: 4, kisi: 'aslan-kosele', dekor: ['ot','tas','saman'],
            metin: 'Fındık kayanın üstünde zıplarken Kösele uyandı ve upuzun esneyip kükredi. Otlakta sesler birbirine karıştı: kim ne dedi, kim nereden seslendi?', soz: 'Hıııı… Burnumda zıplayan kim?' }, gorev: 'dizi',
          yonerge: 'Otlağın sesleri sırayla geliyor. Dinleyip aynı sırayla dokunalım.',
          dostlar: [ { sekil: 'inek', ad: 'Kösele' }, { sekil: 'tavsan', ad: 'Fındık' },
                     { sekil: 'fok', ad: 'Toz' }, { sekil: 'kus', ad: 'Kanat' } ],
          uzunluklar: [ 2, 3, 4 ],
          cozum: 'Sesler ayırt edildi. Kösele kükredi ama sonra… durdu.' }
      ],
      final: { engel: 'Fındık korkudan titriyor. Onu sakinleştirmek gerek.',
               sahne: { tip: 'istek', nesne: 'kalp', adet: 3, kisi: 'fare-findik', dekor: ['ot','saman','tas'],
               metin: 'Kösele’nin sesi öyle büyüktü ki Fındık kulaklarını kapayıp bir taşın arkasına sindi. Kösele bunu görünce sesini alçalttı.', soz: 'Biri bana sarılır mı?' }, etkinlik: 'sev',
               cozum: 'Kösele başını eğdi: “Kusura bakma, bağırdım.” Fındık gülümsedi ve ona bir buğday tanesi verdi.' }
    },
    {
      kod: 'kayalik', asamaSonu: 'Haber ulaştı — koloni yola çıktı', ad: 'Kayalık', baslik: 'Gözcü uyarır',
      renk: '#A79279', acik: '#EAE0CE', gok: '#F4EEE2', zemin: '#C2B392',
      hikaye: 'Otlağın ucunda kayalık başlar. Yukarıdan bütün ova görünür. Gözcü kartal Kanat sabahtan beri tedirgin: uzakta, ağaçların dibinde daha önce hiç görmediği bir şey var — düğümlü, kalın bir ağ.',
      soz: '“Yüksekten bakan, uzaktaki tehlikeyi önce görür.”',
      karakter: { kod: 'kartal-kanat', ad: 'Kanat', tur: 'Gözcü kartal' },
      sozler: [ 'Ben Kanat. Buradan her şeyi görürüm.', 'İyi gidiyor — yol açılıyor.', 'Haber ulaştı. Şimdi acele etmeliyiz!' ],
      armagan: { kod: 'tas', ad: 'Keskin taş', renk: '#8E9AA5' },
      engeller: [
        { engel: 'Kayalığa çıkan basamaklar dağılmış.',
          sahne: { tip: 'sorun', nesne: 'kaya2', adet: 4, kisi: 'kartal-kanat', dekor: ['tas','bulut','ot'],
            metin: 'Kayalığa çıkan taş basamaklar gece yuvarlanıp dağılmış. Fareler için her basamak kocaman; sırayla dizilmezse kimse tırmanamaz.', soz: 'Küçükten büyüğe dizelim.' }, gorev: 'sirala',
          yonerge: 'Basamakları küçükten büyüğe dizelim ki tırmanmak kolay olsun.',
          ogeler: [ { ad: 'En küçük', sekil: 'kaya1' }, { ad: 'Küçük', sekil: 'kaya2' },
                    { ad: 'Büyük', sekil: 'kaya3' }, { ad: 'En büyük', sekil: 'kaya4' } ],
          cozum: 'Basamaklar dizildi; kayalığa çıkılabilir.' },
        { engel: 'Kanat’ın gözcü çantasından bir şey eksiliyor.',
          sahne: { tip: 'kesif', nesne: 'kazik2', adet: 3, kisi: 'kartal-kanat', dekor: ['tas','bulut','kaya3'],
            metin: 'Kanat gözcü çantasını kayanın üstüne boşalttı: keskin taş, ip, su, buğday, yaprak. Saydı, bir daha saydı; biri kayıp gibi.', soz: 'Bir şey eksik ama ne?' }, gorev: 'kayip',
          yonerge: 'Çantaya iyi bakalım. Gözümüzü kapayıp açınca ne eksildi, bulalım.',
          tur: 2,
          ogeler: [ { ad: 'Keskin taş', sekil: 'tas' }, { ad: 'İp', sekil: 'kazik2' },
                    { ad: 'Su', sekil: 'su' }, { ad: 'Buğday', sekil: 'tohum' },
                    { ad: 'Yaprak', sekil: 'yaprak' } ],
          cozum: 'Eksilen bulundu; çanta yeniden tamam.' },
        { engel: 'Kayalıkta ova gibi görünmeyen bir şey var.',
          sahne: { tip: 'kesif', nesne: 'tas', adet: 5, kisi: 'kartal-kanat', dekor: ['tas','ot','bulut'],
            metin: 'Kayalığın dibinde taşların arasına poşetler, kabuklar, yapraklar karışmış. Kanat keskin taşları arıyor; ileride çok lazım olacaklar.', soz: 'Yalnızca keskin taşlar!' }, gorev: 'refleks',
          yonerge: 'Kanat hızlı hızlı gösteriyor. Yalnızca taşa dokun; başkası gelirse elini çek.',
          hedef: 8, gorunme: 1050, ara: 320,
          aranan: { sekil: 'tas', ad: 'Keskin taş' },
          digerleri: [ { sekil: 'poset', ad: 'Poşet' }, { sekil: 'kabuk', ad: 'Kabuk' }, { sekil: 'yaprak', ad: 'Yaprak' } ],
          cozum: 'Keskin taşlar ayrıldı; ağı kesmek için onlar gerekecek.' },
        { engel: 'Uzaktaki hareket gözden kaçmamalı.',
          sahne: { tip: 'kesif', nesne: 'bulut', adet: 3, kisi: 'kartal-kanat', dekor: ['tas','bulut','agac'],
            metin: 'Kanat kayalığın en tepesinden ovaya bakıyor. Uzakta, ağaçların dibinde bir şey kıpırdıyor; gözünü ondan ayırmamalı.', soz: 'Orada bir şey var…' }, gorev: 'takip',
          yonerge: 'Uzakta bir hareket var. Parmağını üstüne koy ve gözden kaçırmadan takip et.',
          sekil: 'kartal-kanat', sure: 5400, hiz: .8, boy: 13,
          cozum: 'Hareket izlendi: avcılar ağı bırakıp gitti, Kösele içinde kaldı.' },
        { engel: 'Kanat’ın taşıyacağı yük iki yana eşit bölünmeli.',
          sahne: { tip: 'istek', nesne: 'tas', adet: 4, kisi: 'kartal-kanat', dekor: ['tas','bulut','ot'],
            metin: 'Kanat keskin taşları koloniye taşıyacak. Ama pençesindeki iki torbadan biri ağır gelirse havada yan yatar.', soz: 'İki yanı eşit olmalı.' }, gorev: 'terazi',
          yonerge: 'Sağ kefeye ekleyip dengeleyelim. Fazla gelirse geri alırız.',
          sol: [ { sekil: 'tas', agirlik: 2 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'Yük dengelendi; Kanat rahat uçacak.' },
        { engel: 'Kanat haberi tam zamanında bırakmalı.',
          sahne: { tip: 'gelis', nesne: 'yaprak', adet: 3, kisi: 'kartal-kanat', dekor: ['bulut','tas','yuva'],
            metin: 'Kanat haberi bir yaprağa sardı: Kösele bir ağa takılmış! Yaprağı yuvanın tam üstünden geçerken bırakmalı ki doğru yere düşsün.', soz: 'Yuvanın üstündeyken söyleyin!' }, gorev: 'zaman',
          yonerge: 'Kanat yuvanın üstündeyken haberi bırakalım — acelemiz yok.',
          tasiyici: 'kartal', tasiyiciAd: 'Kanat', yuk: 'yaprak',
          hedef: 'yuva', hedefAd: 'Koloni yuvası', genislik: 30, hiz: 1.1, hedefSayisi: 3,
          cozum: 'Haber yuvaya ulaştı: “Kösele ağa düştü!”' }
      ],
      final: { engel: 'Kanat bütün gün uçtu, kanatları yoruldu.',
               sahne: { tip: 'gelis', nesne: 'bulut', adet: 3, kisi: 'kartal-kanat', dekor: ['tas','bulut','kaya3'],
               metin: 'Haber yuvaya ulaştı, koloni yola çıktı. Kanat kayalığa kondu; tüyleri rüzgârdan karmakarışık olmuş.', soz: 'Tüylerimi düzeltir misiniz?' }, etkinlik: 'timarla',
               cozum: 'Kanat tüylerini düzeltti. “Keskin taş sizde kalsın,” dedi. “İşinize yarayacak.”' }
    },
    {
      kod: 'nehir', asamaSonu: 'Su taşındı — Kösele\'de güç var', ad: 'Nehir', baslik: 'Su taşınır',
      renk: '#5EA8B2', acik: '#D8EEF0', gok: '#E9F6F7', zemin: '#93C3BC',
      hikaye: 'Kösele ağın içinde, kıpırdayamıyor ve susuzluktan bitkin. Fareler ona ulaşmadan önce su taşımalı — yoksa kurtarma başlamadan bitecek. Nehir uzak, kaplar küçük, yol taşlı.',
      soz: '“Bir yudum su, bazen bütün gücü geri getirir.”',
      karakter: { kod: 'aslan-kosele', ad: 'Kösele', tur: 'Aslan' },
      sozler: [ 'Kıpırdayamıyorum… ve çok susadım.', 'Bu su çok iyi geldi. Teşekkür ederim.', 'Küçüklermiş diye düşünmüştüm. Ne kadar yanılmışım.' ],
      armagan: { kod: 'su', ad: 'Serin su', renk: '#3FA9E0' },
      engeller: [
        { engel: 'Su kapları kırılmış.',
          sahne: { tip: 'sorun', nesne: 'sise', adet: 4, kisi: 'fare-findik', dekor: ['su','ot','tas'],
            metin: 'Fareler nehre koştu ama su kaplarından biri yolda çatlamış, parçaları çimenin üstüne dağılmış.', soz: 'Bununla su taşıyamayız.' }, gorev: 'yapboz',
          yonerge: 'Parçaları yerine koyup su kabını birlikte tamamlayalım.',
          resim: 'sise', satir: 2, sutun: 2,
          cozum: 'Kap onarıldı; artık su taşıyabiliriz.' },
        { engel: 'Nehre inen yol kaygan.',
          sahne: { tip: 'gelis', nesne: 'toprak', adet: 4, kisi: 'fare-findik', dekor: ['su','tas','ot'],
            metin: 'Nehre inen yamaç çamur içinde, arada kaygan taşlar var. Fındık minik ayaklarıyla nereye basacağını dikkatle seçmeli.', soz: 'Nereden geçeyim?' }, gorev: 'yol',
          yonerge: 'Çamura değmeden Fındık’ı suya götürelim.',
          baslangic: { x: 100, y: 220, sekil: 'fare-findik', ad: 'Fındık' },
          bitis: { x: 905, y: 220, sekil: 'su', ad: 'Nehir' },
          engeller: [ { x: 330, y: 120, r: 86, sekil: 'toprak', ad: 'Çamur' },
                      { x: 420, y: 330, r: 82, sekil: 'tas', ad: 'Kaygan taş' },
                      { x: 640, y: 160, r: 88, sekil: 'toprak', ad: 'Çamur' },
                      { x: 700, y: 360, r: 78, sekil: 'tas', ad: 'Kaygan taş' } ],
          cozum: 'Fındık suya ulaştı; kaplar dolduruluyor.' },
        { engel: 'Taşınan su dört fareye eşit bölünmeli.',
          sahne: { tip: 'istek', nesne: 'su', adet: 6, kisi: 'fare-findik', dekor: ['su','ot','kabuk'],
            metin: 'Kaplar doldu. Yol uzun, dört taşıyıcı var. Birinin kabı dolu, ötekinin boş olursa yolda susayan olur.', soz: 'Eşit bölelim, hepimiz taşıyalım.' }, gorev: 'paylas',
          yonerge: 'Dördüne de eşit düşsün ki kimse yolda susamasın.',
          dostlar: [ { sekil: 'tavsan', ad: 'Fındık' }, { sekil: 'sincap', ad: 'Toz' },
                     { sekil: 'kus', ad: 'Kanat' }, { sekil: 'kaplumbaga', ad: 'Ağır' } ],
          yem: 'su', yemAd: 'Su', adet: 12,
          cozum: 'Dördü de eşit pay aldı; yola çıkılabilir.' },
        { engel: 'Kaplar sığdan derine dizilecek.',
          sahne: { tip: 'sorun', nesne: 'kabuk2', adet: 4, kisi: 'fare-findik', dekor: ['su','kabuk','ot'],
            metin: 'Nehrin kıyısında büyüklü küçüklü kabuk kaplar karmakarışık duruyor. Hangisi önce dolacak, hangisi sonra, kimse bilmiyor.', soz: 'Küçükten büyüğe dizelim.' }, gorev: 'sirala',
          yonerge: 'Kapları küçükten büyüğe dizelim ki sıra karışmasın.',
          ogeler: [ { ad: 'En küçük', sekil: 'kabuk1' }, { ad: 'Küçük', sekil: 'kabuk2' },
                    { ad: 'Büyük', sekil: 'kabuk3' }, { ad: 'En büyük', sekil: 'kabuk4' } ],
          cozum: 'Kaplar sıralandı; taşıma düzene girdi.' },
        { engel: 'Suda yüzen ile batan karışmış.',
          sahne: { tip: 'kesif', nesne: 'yaprak', adet: 5, kisi: 'fare-toz', dekor: ['su','kabuk','tas'],
            metin: 'Toz’un bir fikri var: suyu bir salın üstüne koyup nehirden aşağı yüzdürmek. Ama sal için yüzen şeyler lazım; hangileri yüzer?', soz: 'Bir sal yapalım!' }, gorev: 'ayir',
          yonerge: 'Hangisi suda yüzer, hangisi batar? Birlikte deneyelim.',
          kutular: ['Suda yüzer', 'Suya batar'],
          ogeler: [ { ad: 'Yaprak', sekil: 'yaprak', dogru: 0 }, { ad: 'Dal', sekil: 'dal2', dogru: 0 },
                    { ad: 'Kabuk', sekil: 'kabuk', dogru: 0 }, { ad: 'Taş', sekil: 'tas', dogru: 1 },
                    { ad: 'Palamut', sekil: 'palamut', dogru: 1 }, { ad: 'Kozalak', sekil: 'kozalak', dogru: 1 } ],
          cozum: 'Yüzenlerden bir sal kuruldu; su daha çabuk taşınıyor.' },
        { engel: 'Kime ne kadar su gerektiği karışmış.',
          sahne: { tip: 'istek', nesne: 'kabuk3', adet: 4, kisi: 'aslan-kosele', dekor: ['su','ot','tas'],
            metin: 'Kaplar ağın yanına getirildi ama kapakları kapalı; hangisi hangisinin eşi, karıştı. Kösele ağın içinden sabırla bekliyor.', soz: 'Acele yok… ama çok susadım.' }, gorev: 'cift',
          yonerge: 'Kaplar kapalı duruyor. İki kart çevir, aynıysa açık kalır — yerlerini aklında tut.',
          cift: [ 'kabuk1', 'kabuk2', 'kabuk3', 'kabuk4', 'su', 'sise' ],
          cozum: 'Kaplar eşleşti; herkes kendi payını aldı.' }
      ],
      final: { engel: 'Kösele susuz ve bitkin. Ona su vermek gerek.',
               sahne: { tip: 'istek', nesne: 'su', adet: 5, kisi: 'aslan-kosele', dekor: ['su','ot','tas'],
               metin: 'Fareler kapları tek tek ağın yanına dizdi. Kösele başını zor kaldırıyor ama suyu görünce gözleri parladı.', soz: 'Bir yudum… lütfen.' }, etkinlik: 'besle', yem: 'su',
               cozum: 'Kösele kana kana içti ve gözlerini açtı. “Şimdi,” dedi, “beni buradan çıkarabilir misiniz?”' }
    },
    {
      kod: 'kamp', asamaSonu: 'Son ip koptu', ad: 'Ağ', baslik: 'Ağ çözülür',
      renk: '#8E7B63', acik: '#E6DCC8', gok: '#F2EBDC', zemin: '#B8A684',
      hikaye: 'Sıra en zor işte. Ağ kalın, düğümler sıkı, ipler çok. Tek bir fare bunu bir haftada kesemez. Ama bütün koloni buradaysa iş değişir. Her düğüm bir çocuğun sırası.',
      soz: '“Bir düğümü tek başına çözemezsin. Ama hepimiz varsak, düğüm kalmaz.”',
      karakter: { kod: 'fare-toz', ad: 'Toz', tur: 'Bilge fare' },
      sozler: [ 'Ben Toz. Sakin olun, plan bende.', 'Düğümler açılıyor, devam!', 'Son düğüm de gitti. Kösele özgür!' ],
      armagan: { kod: 'kalp', ad: 'Özgürlük', renk: '#DF9B9C' },
      engeller: [
        { engel: 'Ağ hangi düğümden çözülecek, karışık.',
          sahne: { tip: 'kesif', nesne: 'kazik2', adet: 6, kisi: 'fare-toz', dekor: ['agac','ot','tas'],
            metin: 'Toz ağın çevresinde bir tur attı. Düğümler çok ama hepsi aynı değil: doğru olanlardan başlarsak ağ kendiliğinden gevşer.', soz: 'Gösterdiklerimi aklınızda tutun.' }, gorev: 'takimyildiz',
          yonerge: 'Toz düğümleri tek tek gösteriyor. Hangileri parladıysa aynılarına dokun.',
          nokta: 12, yanan: 4, tur: 2, bakma: 2400,
          cozum: 'Düğüm sırası akılda kaldı; doğru yerden başlıyoruz.' },
        { engel: 'İpler rüzgârda sallanıyor, nişan almak zor.',
          sahne: { tip: 'sorun', nesne: 'kazik2', adet: 4, kisi: 'fare-toz', dekor: ['agac','ot','bulut'],
            metin: 'Rüzgâr çıktı; ağın ipleri bir sağa bir sola sallanıyor. Keskin taşla bir düğüme dokunmak için tam anı yakalamak gerek.', soz: 'Gözünüz düğümde olsun!' }, gorev: 'isabet',
          yonerge: 'İpler rüzgârda sallanıyor. Gezinen düğümlere tam üstünden dokun.',
          sekil: 'kazik2', hedef: 7, adet: 4, hiz: .7, boy: 12,
          cozum: 'Sallanan düğümlerin hepsi kesildi; ağ gevşedi.' },
        { engel: 'Ağın altındaki taşlar dengeyi bozuyor.',
          sahne: { tip: 'sorun', nesne: 'tas', adet: 5, kisi: 'aslan-kosele', dekor: ['agac','ot','tas'],
            metin: 'Ağın bir kenarına taşlar yığılmış. Ağ kalkarken bir yanı ağır gelirse Kösele’nin patisine takılabilir.', soz: 'Yavaş olun, patim burada.' }, gorev: 'terazi',
          yonerge: 'İki yanı eşitleyelim ki ağ kalkarken Kösele’ye zarar gelmesin.',
          sol: [ { sekil: 'tas', agirlik: 3 }, { sekil: 'tas', agirlik: 2 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'Denge kuruldu; ağ güvenle kaldırılabilir.' },
        { engel: 'Ağın parçaları birbirine dolanmış.',
          sahne: { tip: 'kesif', nesne: 'yuva', adet: 3, kisi: 'fare-toz', dekor: ['agac','ot','kazik2'],
            metin: 'Toz ağın bir köşesini açtı ve düşünmeye başladı: ipler birbirine dolanmış, desen karmakarışık. Hangi parça nereye gidiyor?', soz: 'Önce düzeni çözelim.' }, gorev: 'yapboz',
          yonerge: 'Parçaları yerine koyup ağın düzenini çözelim.',
          resim: 'yuva', satir: 2, sutun: 3,
          cozum: 'Ağın düzeni çözüldü; nereden keseceğimiz belli.' },
        { engel: 'Ağın altında kalanlar var.',
          sahne: { tip: 'kesif', nesne: 'ot', adet: 5, kisi: 'fare-toz', dekor: ['agac','ot','yaprak'],
            metin: 'Ağın altında yalnız Kösele yok. Küçük dostlar da iplerin arasına girmiş, otların içinde kalmış.', soz: 'Hepsini bulalım.' }, gorev: 'gizli',
          yonerge: 'Ağın altına iyi bakalım — sıkışan dostları bulalım.',
          tohum: 53, sus: 30, susBoy: [4, 8], boy: 11,
          gizli: [ { sekil: 'sincap', ad: 'Sincap', x: 18, y: 60, a: -10 },
                   { sekil: 'kaplumbaga', ad: 'Kaplumbağa', x: 74, y: 28, a: 8 },
                   { sekil: 'kus', ad: 'Kuş', x: 45, y: 74, a: 15 },
                   { sekil: 'baykus', ad: 'Baykuş', x: 63, y: 58, a: -14 } ],
          cozum: 'Ağın altında kalan herkes çıkarıldı.' },
        { engel: 'Son düğüm tam zamanında kesilmeli.',
          sahne: { tip: 'istek', nesne: 'kazik2', adet: 2, kisi: 'fare-findik', dekor: ['agac','ot','tas'],
            metin: 'Geriye kalın bir düğüm kaldı. Fındık ipin üstünde bir o yana bir bu yana koşuyor; tam düğümün üstündeyken kesmeli.', soz: 'Hazırım, söyleyin!' }, gorev: 'zaman',
          yonerge: 'Fındık düğümün üstündeyken keselim — acelemiz yok.',
          tasiyici: 'fare-findik', tasiyiciAd: 'Fındık', yuk: 'tas',
          hedef: 'kazik2', hedefAd: 'Son düğüm', genislik: 26, hiz: 1.2, hedefSayisi: 3,
          cozum: 'Son düğüm koptu. Ağ Kösele’nin üstünden kaydı.' }
      ],
      final: { engel: 'Kösele ağdan çıktı ama tüyleri karmakarışık.',
               sahne: { tip: 'cozuldu', nesne: 'kalp', adet: 5, kisi: 'aslan-kosele', dekor: ['agac','ot','tas'],
               metin: 'Son ip de koptu ve ağ yere kaydı. Kösele ayağa kalktı; yelesi karmakarışık, içine otlar, ip parçaları dolmuş.', soz: 'Özgürüm! Ama yelem ne hâlde…' }, etkinlik: 'timarla',
               cozum: 'Kösele ayağa kalktı, gerindi ve kükredi — ama bu sefer sevinçten.' }
    }
  ],

  kapanis: {
    baslik: 'En küçüğü, en büyüğünü kurtardı.',
    metin: 'Kösele ağdan çıktığında ilk yaptığı şey kükremek değildi. Eğildi, Fındık’ı avucuna aldı ve “sen benim en büyük dostumsun” dedi.\n\nO gün otlakta bir şey değişti. Kimse bir daha “sen çok küçüksün” demedi. Çünkü herkes gördü ki bir ağı çözen şey pençenin büyüklüğü değil, yardıma gelenlerin sayısıydı.\n\nKösele artık kayada uyurken bir gözünü açık tutuyor — birinin yardıma ihtiyacı var mı diye.',
    ders: 'En küçük dost, en büyük yardımı yapabilir.'
  }
};
