/* MASAL 01 — AĞUSTOS BÖCEĞİ İLE KARINCA (Ezop)
   ────────────────────────────────────────────
   Kaynak kamu malı: Ezop (~MÖ 600), La Fontaine (ö. 1695). Metin bana ait,
   çeviri değil — telif sorunu yok.

   NEDEN BU MASAL BİRİNCİ: Fablın kendisi iki dakika sürer. Ama olay örgüsü
   "kışa hazırlanmak" üzerine kurulu ve hazırlık, doğası gereği ONLARCA iş
   demek: toplamak, ayıklamak, tartmak, taşımak, depolamak, paylaşmak.
   40 dakikayı dolduran şey dolgu değil, masalın kendi işi.

   FİNALİ DEĞİŞTİRDİM — bilerek. Ezop'ta karıncalar ağustos böceğini kovar,
   böcek açlıktan ölür. 3-6 yaş için bu ders değil, korku. Bizim finalde
   karıncalar kapıyı açar ve erzağı paylaşır; ağustos böceği de bütün kış
   onlara şarkı söyler. Böylece iki ders birden kalır:
     "Hazırlık emektir" ve "Paylaşmak dostluktur."
   Ağustos böceğinin yeteneği de değersiz değil — sadece zamanı yanlıştı.

   YAPI: dört mevsim = dört bölüm. Durak sayısı sınıf mevcudu kadar.
   Her bölümün sonunda bir armağan; dördü birleşince kış atlatılır. */

export default {
  kod: 'karinca',
  ad: 'Ağustos Böceği ile Karınca',
  kaynak: 'Ezop fablı',
  ders: 'Hazırlık emektir, paylaşmak dostluktur',
  sure: '40 dakika · bütün sınıf',
  ozet: 'Bir yaz boyunca karıncalarla kışa hazırlanır, kış gelince kapıyı ağustos böceğine açarsınız.',
  renk: '#E2A34E',
  ikon: 'saman',

  /* Dünya: ada değil, bir tarla. Mevsim ilerledikçe rengi değişir. */
  /* Mekân: bir tarla. Dört çeyrek dört mevsim; ortada dolan ambar. */
  dunya: { mekan: 'tarla', gok: 0xdce9ef, cevre: 0x9dbb7e, piyon: 0xc98f4e ,
    /* Çözülen her durak tarlaya bir filiz diker — sınıf ilerledikçe
       tarla gerçekten yeşeriyor, sadece sayaç artmıyor. */
    izNotu: { bos: 'Tarla henüz boş', dolu: '{n} filiz dikildi · ambar doluyor' },
    iz: 'filiz', izRenk: 0x8cc46e, kesifRenk: 0xd8a34f,
    /* Tıklanabilir ayrıntılar. Ders içeriği değil, dünyanın kendi
       hikâyesi — öğretmen duraklar arasında bunlardan açıp anlatabilir. */
    kesif: [
      { x: -4.6, z: -5.4, ikon: 'kalem', ad: 'Korkuluk',
        metin: 'Bu korkuluğu Kıvırcık’ın dedesi dikmiş. Şapkası her ilkbahar yenilenir. Kuşlar aslında ondan korkmuyor — sadece şaşırıp başka tarlaya konuyorlar.' },
      { x: 0, z: 3.4, ikon: 'kutu', ad: 'Ambar',
        metin: 'Ambarın tabanı yerden yüksek. Karıncalar böyle yapıyor çünkü yağmur suyu içeri girmesin, altından rüzgâr geçip erzak kurusun istiyorlar.' },
      { x: -9.8, z: -6.6, ikon: 'fidan', ad: 'İlkbahar ağacı',
        metin: 'Koloninin en yaşlı ağacı. Kıvırcık ilk yürüdüğü günü bu ağacın gölgesinde öğrenmiş. Her bahar önce bu ağaç çiçek açar, sonra tarla ekilir.' },
      { x: 5.6, z: 3.6, ikon: 'ot', ad: 'Hasat çuvalları',
        metin: 'Çuvallar sonbaharda tarlada bekletilir; içindeki nem uçsun diye. Pençe her akşam gelip elini üstlerine koyar, soğuduklarında ambara taşınırlar.' },
      { x: -9.4, z: 6.8, ikon: 'bulut', ad: 'Kış ağacı',
        metin: 'Kışın çıplak duran bu ağaç aslında uyuyor. Fısıltı ilk geldiği gece tam buranın altında titriyordu — karıncalar onu buradan alıp yuvaya götürdü.' }
    ]},


  acilis: [
    { tag: 'BİR VARMIŞ, BİR YOKMUŞ', baslik: 'Uzun bir yaz başlıyor.', ikon: 'isik',
      metin: 'Tarlanın kenarındaki karınca yuvasında telaş var. Kış uzaktaymış gibi görünüyor ama karıncalar bilir: kış her yıl gelir ve kimseyi beklemez. Bu yaz çok iş var.' },
    { tag: 'İKİ KOMŞU', baslik: 'Biri çalışır, biri şarkı söyler.', ikon: 'kus',
      metin: 'Çitin öbür yanında Ağustos Böceği yaşar. Kemanı vardır ve bütün gün çalar. Karıncalar onun şarkısını sever ama durup dinleyecek vakitleri yoktur. “Sen de hazırlansana,” derler. Ağustos Böceği güler: “Daha çok var!”' },
    { tag: 'BU MASALIN KAHRAMANI SİZSİNİZ', baslik: 'Dört mevsim, tek bir ambar.', ikon: 'kutu',
      metin: 'Sırayla tarlaya ineceğiz. İlkbaharda ekecek, yazın toplayacak, sonbaharda depolayacağız. Kış geldiğinde ambar doluysa kimse üşümez. Kapıyı kimin için açacağımıza da hep birlikte karar vereceğiz.' }
  ],

  bolumler: [
    {
      kod: 'ilkbahar', ad: 'İlkbahar', baslik: 'Tarlayı uyandır',
      renk: '#7FB069', acik: '#DDEFC4', gok: '#EAF6E0', zemin: '#BFDB7A',
      hikaye: 'Karlar eridi, toprak yumuşadı. Tarlayı ekime hazırlamak için önce taşları toplamak, tohumları ayırmak ve suyu getirmek gerek. Bu ay ne ekersek, kışın onu yeriz.',
      soz: '“Tohum küçüktür ama içinde bütün bir yaz saklıdır.”',
      karakter: { kod: 'karinca-isci', ad: 'Kıvırcık', tur: 'İşçi karınca' },
      sozler: [ 'Ben Kıvırcık! Tarlayı birlikte uyandıralım mı?', 'Çok iyi gidiyoruz, toprak hazırlanıyor!', 'Bitti! Bu tarla artık ekime hazır.' ],
      armagan: { kod: 'tohum', ad: 'Tohum', renk: '#BD8451' },
      engeller: [
        { engel: 'Kışın taşıdığı taşlar tarlayı kaplamış.',
          sahne: { tip: 'sorun', nesne: 'tas', adet: 5, kisi: 'karinca-isci', dekor: ['fidan','ot','kozalak'],
            metin: 'Kar eridi, toprak göründü — ama kışın sürüklediği taşlar bütün tarlayı kaplamış. Kıvırcık sabana bakıyor: böyle geçemez.', soz: 'Bunları kaldırmadan ekemeyiz!' }, gorev: 'say',
          yonerge: 'Toprağı birlikte temizleyelim — taşları kenara taşıyalım.',
          sayi: 5, sekil: 'tas', cozum: 'Tarla temizlendi; saban artık geçebilir.' },
        { engel: 'Tohum çuvalları birbirine karışmış.',
          sahne: { tip: 'kesif', nesne: 'tohum', adet: 6, kisi: 'karinca-isci', dekor: ['kutu','ot','fidan'],
            metin: 'Çuvallar kış boyunca ambarda üst üste durmuş. Kapaklar açılınca içindekiler birbirine karışmış: toprağa girecekler de, girmeyecekler de.' }, gorev: 'ayir',
          yonerge: 'Hangisi toprağa girer, hangisi girmez? Birlikte ayıralım.',
          kutular: ['Toprağa ekilir', 'Ekilmez'],
          ogeler: [ { ad: 'Buğday', sekil: 'tohum', dogru: 0 }, { ad: 'Palamut', sekil: 'palamut', dogru: 0 },
                    { ad: 'Kozalak', sekil: 'kozalak', dogru: 0 }, { ad: 'Taş', sekil: 'tas', dogru: 1 },
                    { ad: 'Şişe', sekil: 'sise', dogru: 1 }, { ad: 'Ayakkabı', sekil: 'ayakkabi', dogru: 1 } ],
          cozum: 'Tohumlar ayrıldı; çuvallar ekime hazır.' },
        { engel: 'Su kanalı tarlaya ulaşmıyor.',
          sahne: { tip: 'gelis', nesne: 'su', adet: 4, kisi: 'karinca-isci', dekor: ['tas','fidan','ot'],
            metin: 'Dere akıyor ama kanal tarlaya varmadan kayalara takılıyor. Toprak susuz; tohum atsak bile çıkmaz.', soz: 'Suyu buraya getirmeliyiz.' }, gorev: 'yol',
          yonerge: 'Kıvırcık için kayalara değmeden bir su yolu çizelim.',
          baslangic: { x: 105, y: 220, sekil: 'karinca-isci', ad: 'Kıvırcık' }, bitis: { x: 900, y: 220, sekil: 'fidan', ad: 'Tarla' },
          engeller: [ { x: 400, y: 130, r: 88, sekil: 'tas', ad: 'Kaya' },
                      { x: 620, y: 320, r: 88, sekil: 'tas', ad: 'Kaya' } ],
          cozum: 'Su tarlaya ulaştı; toprak kana kana içti.' },
        { engel: 'Tohumlar üç tarlaya bölünecek ama nasıl?',
          sahne: { tip: 'istek', nesne: 'tohum', adet: 6, kisi: 'karinca-isci', dekor: ['fidan','ot','kutu'],
            metin: 'Üç tarla var, bir çuval tohum. Birine çok verirsek öbürü boş kalır; kışın da o kadar eksik yeriz.', soz: 'Eşit bölelim, olur mu?' }, gorev: 'paylas',
          yonerge: 'Üç tarlaya eşit tohum düşsün; hiçbiri aç kalmasın.',
          dostlar: [ { sekil: 'fidan', ad: 'Doğu tarlası' }, { sekil: 'fidan', ad: 'Orta tarla' }, { sekil: 'fidan', ad: 'Batı tarlası' } ],
          yem: 'tohum', yemAd: 'Tohum', adet: 9,
          cozum: 'Üç tarla da eşit tohum aldı.' },
        { engel: 'Hangi tohumdan ne çıkar, karıncalar unutmuş.',
          sahne: { tip: 'kesif', nesne: 'palamut', adet: 4, kisi: 'karinca-isci', dekor: ['agac','fidan','kozalak'],
            metin: 'Kış uzun sürdü, koloni unutmuş: hangi tohumdan ne çıkıyordu? Yanlış yere ekersek bütün yaz boşa gider.' }, gorev: 'eslestir',
          yonerge: 'Tohumları büyüyünce olacakları şeyle eşleştirelim.',
          ciftler: [ { a: 'Palamut', asekil: 'palamut', b: 'Meşe ağacı', bsekil: 'agac' },
                     { a: 'Kozalak', asekil: 'kozalak', b: 'Çam fidanı', bsekil: 'fidan' },
                     { a: 'Buğday tanesi', asekil: 'tohum', b: 'Başak', bsekil: 'ot' },
                     { a: 'Elma çekirdeği', asekil: 'tohum', b: 'Elma', bsekil: 'elma' } ],
          cozum: 'Her tohum kendi geleceğini buldu.' },
        { engel: 'Saban izleri bir düzene göre açılmalı.',
          sahne: { tip: 'gelis', nesne: 'ot', adet: 5, kisi: 'karinca-isci', dekor: ['fidan','tohum','ot'],
            metin: 'Kıvırcık sabanı tarlanın başına getirdi. Sıralar rastgele açılırsa kökler birbirini boğar — bir düzen gerek.' }, gorev: 'oruntu',
          yonerge: 'Sıraya bak: buğday, ot, buğday, ot… boşluğa hangisi geliyor?',
          dizi: [ 'tohum', 'ot', 'tohum', 'ot', null, null, 'tohum' ],
          cevaplar: [ 'tohum', 'ot' ],
          secenekler: [ { sekil: 'tohum', ad: 'Buğday' }, { sekil: 'ot', ad: 'Ot' }, { sekil: 'elma', ad: 'Elma' } ],
          cozum: 'Tarla düzenle ekildi; her sıra yerini buldu.' }
      ],
      final: { engel: 'Kıvırcık sabahtan beri hiç durmadı.',
               sahne: { tip: 'istek', nesne: 'ot', adet: 3, kisi: 'karinca-isci', dekor: ['fidan','ot','tohum'],
               metin: 'Tarla ekildi, su geldi, sıralar düzene girdi. Kıvırcık kürek elinde duruyor — sabahtan beri bir kez bile oturmadı.', soz: 'Biraz karnımı doyurabilir miyim?' }, etkinlik: 'besle', yem: 'tohum',
               cozum: 'Kıvırcık dinlendi. “İlk armağan sizin,” dedi ve avucuna bir tohum koydu.' }
    },
    {
      kod: 'yaz', ad: 'Yaz', baslik: 'Hasat zamanı',
      renk: '#E2A34E', acik: '#FFE8B8', gok: '#FFF4DC', zemin: '#E8D98A',
      hikaye: 'Başaklar sarardı, güneş tepede. Ağustos Böceği çitin üstünde keman çalıyor; karıncalar sırtlarında yüklerle geçiyor. Hasat kısa sürer — kaçırılan tane kışın eksik kalır.',
      soz: '“Yazın bir tane, kışın bir öğündür.”',
      karakter: { kod: 'karinca-asker', ad: 'Pençe', tur: 'Bekçi karınca' },
      sozler: [ 'Ben Pençe, hasadın bekçisi. Hadi başlayalım!', 'Tek tane bile kaybolmuyor, aferin!', 'Hasat tamam. Sepetler ağzına kadar dolu!' ],
      armagan: { kod: 'basak', ad: 'Başak', renk: '#E0B455' },
      engeller: [
        { engel: 'Olgunlaşan başaklar toplanmayı bekliyor.',
          sahne: { tip: 'sorun', nesne: 'ot', adet: 6, kisi: 'karinca-asker', dekor: ['ot','tohum','kutu'],
            metin: 'Güneş tepede, başaklar sarardı. Pençe nöbet yerinden sesleniyor: olgunlaşan tane beklemez, bugün toplanmazsa dökülür.', soz: 'Hasat başlasın!' }, gorev: 'yakala',
          yonerge: 'Rüzgâr başakları savuruyor. Parmağını aşağıda gezdir, sepeti kaydır ve düşenleri tut.',
          hedef: 8, hiz: .18, sikayet: 1150, iyi: [ 'ot', 'tohum' ], kotu: [],
          cozum: 'Sepet doldu; ilk hasat içeride.' },
        { engel: 'Hasat iki sepete bölünecek, eşit olmalı.',
          sahne: { tip: 'istek', nesne: 'kutu', adet: 4, kisi: 'karinca-asker', dekor: ['ot','tohum','fidan'],
            metin: 'İki sepet, iki taşıma kolu. Biri ağır olursa taşıyan karınca yolda devrilir ve tane toprağa dökülür.' }, gorev: 'terazi',
          yonerge: 'Sağ kefeye ekleyip terazi düzelene kadar deneyelim.',
          sol: [ { sekil: 'tas', agirlik: 2 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'İki sepet eşitlendi; yük adilce bölündü.' },
        { engel: 'Sepete buğday olmayan şeyler karışmış.',
          sahne: { tip: 'kesif', nesne: 'tohum', adet: 6, kisi: 'karinca-asker', dekor: ['ot','sise','kutu'],
            metin: 'Tarladan gelen sepetin içinde buğdaydan başka şeyler de var. Ambarda çürüyen bir şey kışın hepsini bozar.' }, gorev: 'refleks',
          yonerge: 'Bant hızlı akıyor. Yalnızca buğdaya dokun; başka bir şey gelirse elini çek.',
          hedef: 8, gorunme: 1100, ara: 330,
          aranan: { sekil: 'tohum', ad: 'Buğday' },
          digerleri: [ { sekil: 'tas', ad: 'Taş' }, { sekil: 'yaprak', ad: 'Yaprak' }, { sekil: 'sise', ad: 'Şişe' } ],
          cozum: 'Bant boşaldı; sepette yalnızca buğday kaldı.' },
        { engel: 'Başakların arasına taneler düşmüş.',
          sahne: { tip: 'kesif', nesne: 'tohum', adet: 5, kisi: 'karinca-asker', dekor: ['ot','yaprak','kozalak'],
            metin: 'Hasat hızlı gitti ama acele döküntü bırakır. Pençe eğilip toprağa bakıyor: her tane kışın bir öğün demek.', soz: 'Tek tane bile kalmasın.' }, gorev: 'gizli',
          yonerge: 'Yere düşen taneleri bulalım — hiçbiri boşa gitmesin.',
          tohum: 41, sus: 26, susBoy: [4, 8], boy: 11,
          gizli: [ { sekil: 'tohum', ad: 'Birinci tane', x: 18, y: 62, a: -9 },
                   { sekil: 'palamut', ad: 'Palamut', x: 76, y: 30, a: 7 },
                   { sekil: 'kozalak', ad: 'Kozalak', x: 47, y: 74, a: 14 } ],
          cozum: 'Düşen taneler toplandı; tek bir tane bile kaybolmadı.' },
        { engel: 'Yükler ağırdan hafife dizilmeli.',
          sahne: { tip: 'sorun', nesne: 'kutu', adet: 4, kisi: 'karinca-asker', dekor: ['ot','tohum','fidan'],
            metin: 'Çuvallar gelişigüzel yığılmış. En ağırı en üstte duruyor ve yığın her an devrilebilir.' }, gorev: 'sirala',
          yonerge: 'Çuvalları küçükten büyüğe dizelim ki taşımak kolay olsun.',
          ogeler: [ { ad: 'En küçük', sekil: 'kazik1' }, { ad: 'Küçük', sekil: 'kazik2' },
                    { ad: 'Büyük', sekil: 'kazik3' }, { ad: 'En büyük', sekil: 'kazik4' } ],
          cozum: 'Çuvallar sıralandı; en ağırı en sona kaldı.' },
        { engel: 'Harman için rüzgârı beklemek gerek.',
          sahne: { tip: 'gelis', nesne: 'tohum', adet: 5, kisi: 'karinca-asker', dekor: ['ot','bulut','kutu'],
            metin: 'Taneyi samandan ayırmanın tek yolu rüzgâr. Ama rüzgâr her an esmez; tam harman yerinin üstünden geçtiğinde savurmak gerek.' }, gorev: 'zaman',
          yonerge: 'Rüzgâr tam harman yerinin üstündeyken savuralım.',
          tasiyici: 'kus', tasiyiciAd: 'Rüzgâr', yuk: 'tohum',
          hedef: 'kutu', hedefAd: 'Harman yeri', genislik: 30, hiz: 1, hedefSayisi: 3,
          cozum: 'Saman uçtu, taneler kaldı; harman tamamlandı.' }
      ],
      final: { engel: 'Pençe bütün gün kapıda nöbet tuttu.',
               sahne: { tip: 'gelis', nesne: 'ot', adet: 4, kisi: 'karinca-asker', dekor: ['ot','tohum','kutu'],
               metin: 'Hasat bitti, sepetler ambara girdi. Pençe hâlâ kapıda; sırtı toz içinde, gözleri yorgun.', soz: 'Bugün tek bir tane bile kaybolmadı.' }, etkinlik: 'timarla',
               cozum: 'Pençe’nin sırtındaki toz silindi. “Başak sizin,” dedi. “Ambarın ilk katı doldu.”' }
    },
    {
      kod: 'sonbahar', ad: 'Sonbahar', baslik: 'Ambarı doldur',
      renk: '#C4763C', acik: '#F6D8B2', gok: '#FBEBD6', zemin: '#D8B481',
      hikaye: 'Yapraklar döküldü, günler kısaldı. Toplanan her şeyin yerine konması gerek — ıslanan çürür, karışan bulunamaz. Ambar iyi düzenlenirse kış kısa gelir.',
      soz: '“Düzenli ambar, uzun kış demektir.”',
      karakter: { kod: 'karinca-tasiyici', ad: 'Tomurcuk', tur: 'Taşıyıcı karınca' },
      sozler: [ 'Ben Tomurcuk. Sırtım güçlü, taşımaya hazırım!', 'Ambar doluyor, biraz daha!', 'Ambar tıka basa dolu. Kış korkutmuyor artık.' ],
      armagan: { kod: 'ambar', ad: 'Dolu ambar', renk: '#A9773F' },
      engeller: [
        { engel: 'Ambarın kapısı kırılmış.',
          sahne: { tip: 'sorun', nesne: 'kutu', adet: 4, kisi: 'karinca-tasiyici', dekor: ['yaprak','kozalak','kutu'],
            metin: 'Yapraklar döküldü, günler kısaldı. Tomurcuk ambara ilk yükü getirdiğinde kapının tahtalarının kırık olduğunu gördü.', soz: 'Böyle rüzgâr alır, erzak ıslanır.' }, gorev: 'yapboz',
          yonerge: 'Parçaları yerine koyup kapıyı birlikte onaralım.',
          resim: 'kutu', satir: 2, sutun: 2,
          cozum: 'Kapı onarıldı; ambar artık rüzgâr almıyor.' },
        { engel: 'Raflara ne konacağı karışmış.',
          sahne: { tip: 'kesif', nesne: 'elma', adet: 6, kisi: 'karinca-tasiyici', dekor: ['kutu','yaprak','ot'],
            metin: 'Her şey ambara girmez. Bazıları bütün kışı çıkarır, bazıları bir haftada çürüyüp yanındakini de bozar.' }, gorev: 'ayir',
          yonerge: 'Kışa dayanan ile çabuk bozulanı ayıralım.',
          kutular: ['Kışa dayanır', 'Çabuk bozulur'],
          ogeler: [ { ad: 'Buğday', sekil: 'tohum', dogru: 0 }, { ad: 'Palamut', sekil: 'palamut', dogru: 0 },
                    { ad: 'Kozalak', sekil: 'kozalak', dogru: 0 }, { ad: 'Elma', sekil: 'elma', dogru: 1 },
                    { ad: 'Ot', sekil: 'ot', dogru: 1 }, { ad: 'Yaprak', sekil: 'yaprak', dogru: 1 } ],
          cozum: 'Raflar ayrıldı; çürüyecek hiçbir şey içeride kalmadı.' },
        { engel: 'Erzak dört ambara eşit bölünmeli.',
          sahne: { tip: 'istek', nesne: 'tohum', adet: 6, kisi: 'karinca-tasiyici', dekor: ['kutu','yaprak','kozalak'],
            metin: 'Dört ambar var. Hepsini bir yere koyarsak, o ambara bir şey olursa kış ortasında aç kalırız.', soz: 'Bölelim ki güvende olsun.' }, gorev: 'paylas',
          yonerge: 'Dört ambara eşit düşsün ki biri boşalırsa diğerleri yetsin.',
          dostlar: [ { sekil: 'kutu', ad: 'Kuzey' }, { sekil: 'kutu', ad: 'Doğu' },
                     { sekil: 'kutu', ad: 'Güney' }, { sekil: 'kutu', ad: 'Batı' } ],
          yem: 'tohum', yemAd: 'Erzak', adet: 12,
          cozum: 'Dört ambar da eşit doldu.' },
        { engel: 'Ambardan bir şey eksiliyor ama kimse göremiyor.',
          sahne: { tip: 'kesif', nesne: 'tohum', adet: 5, kisi: 'karinca-tasiyici', dekor: ['kutu','yaprak','sise'],
            metin: 'Tomurcuk sayıyor, sayıyor ve her seferinde bir eksik çıkıyor. Rafa iyi bakmak lazım — ne kayboluyor?' }, gorev: 'kayip',
          yonerge: 'Rafa iyi bakalım. Gözümüzü kapayıp açınca ne eksildi, bulalım.',
          tur: 2,
          ogeler: [ { ad: 'Buğday', sekil: 'tohum' }, { ad: 'Palamut', sekil: 'palamut' },
                    { ad: 'Kozalak', sekil: 'kozalak' }, { ad: 'Elma', sekil: 'elma' },
                    { ad: 'Şişe', sekil: 'sise' } ],
          cozum: 'Eksilen bulundu — meğer bir fare uğruyormuş. Kapı sıkılaştırıldı.' },
        { engel: 'Ambara dadanan fare kaçıyor.',
          sahne: { tip: 'gelis', nesne: 'kutu', adet: 6, kisi: 'karinca-tasiyici', dekor: ['yaprak','kozalak','kutu'],
            metin: 'Tomurcuk sonunda hırsızı gördü: küçük bir fare raflar arasında koşuyor. Kaçmadan önce nereye gittiğini görmek gerek.' }, gorev: 'takip',
          yonerge: 'Ambara dadanan fare kaçıyor. Parmağını üstüne koy ve kaldırmadan takip et.',
          sekil: 'sincap', sure: 5200, hiz: .7, boy: 14,
          cozum: 'Fare yakalandı ve kibarca dışarı bırakıldı. Ambarın kapısı artık sıkı.' },
        { engel: 'Kış nöbetinin sırası unutulmamalı.',
          sahne: { tip: 'istek', nesne: 'isik', adet: 4, kisi: 'karinca-tasiyici', dekor: ['kutu','yaprak','bulut'],
            metin: 'Kışın biri hep uyanık kalacak. Sıra karışırsa ya biri hiç uyuyamaz ya da bir gece kimse nöbette olmaz.', soz: 'Sırayı ezberleyelim.' }, gorev: 'dizi',
          yonerge: 'Karıncalar nöbet sırasını söylüyor. Dinleyip aynı sırayla tekrarlayalım.',
          dostlar: [ { sekil: 'inek', ad: 'Kıvırcık' }, { sekil: 'tavsan', ad: 'Pençe' },
                     { sekil: 'fok', ad: 'Tomurcuk' }, { sekil: 'kus', ad: 'Fısıltı' } ],
          uzunluklar: [ 2, 3, 4 ],
          cozum: 'Nöbet sırası ezberlendi; kimse unutulmadı.' }
      ],
      final: { engel: 'Tomurcuk bütün sonbahar sırtında yük taşıdı.',
               sahne: { tip: 'istek', nesne: 'kutu', adet: 4, kisi: 'karinca-tasiyici', dekor: ['kutu','yaprak','kozalak'],
               metin: 'Son çuval da rafa kondu. Tomurcuk ambarın kapısına yaslandı — bütün sonbahar bu sırt taşıdı.', soz: 'Ambar dolu. Artık kış gelebilir.' }, etkinlik: 'sev',
               cozum: 'Tomurcuk gülümsedi. “Ambar dolu,” dedi. “Artık kış gelebilir.”' }
    },
    {
      kod: 'kis', ad: 'Kış', baslik: 'Kapıyı kim için açarız?',
      renk: '#6E93AE', acik: '#DCEAF2', gok: '#EDF4F8', zemin: '#CFDDE3',
      hikaye: 'Kar yağdı, tarla bembeyaz. Ambar dolu, yuva sıcak. Ama dışarıda bir keman sesi var — zayıf, titrek, üşümüş. Ağustos Böceği kapıda. Şimdi asıl soru: ne yapacağız?',
      soz: '“Dolu ambarın kapısı, açıldığı kadar değerlidir.”',
      karakter: { kod: 'agustos-bocegi', ad: 'Fısıltı', tur: 'Ağustos böceği' },
      sozler: [ 'Ç-çok üşüdüm… Beni içeri alır mısınız?', 'Isınmaya başladım. İyi ki varsınız.', 'Şimdi sıra bende — size bir şarkı çalayım!' ],
      armagan: { kod: 'dostluk', ad: 'Dostluk', renk: '#D98B72' },
      engeller: [
        { engel: 'Fısıltı karda yolu bulamıyor.',
          sahne: { tip: 'sorun', nesne: 'bulut', adet: 5, kisi: 'agustos-bocegi', dekor: ['bulut','kozalak','tas'],
            metin: 'Kar yağdı, tarla bembeyaz. Kapının önünde titreyen bir keman sesi var — Fısıltı yolu bulamıyor ve parmakları donmuş.', soz: 'Ç-çok üşüdüm…' }, gorev: 'yol',
          yonerge: 'Kar yığınlarına değmeden Fısıltı’yı yuvanın kapısına getirelim.',
          baslangic: { x: 100, y: 220, sekil: 'agustos-bocegi', ad: 'Fısıltı' }, bitis: { x: 905, y: 220, sekil: 'kovuk', ad: 'Yuva' },
          engeller: [ { x: 330, y: 120, r: 86, sekil: 'bulut', ad: 'Kar yığını' },
                      { x: 420, y: 330, r: 82, sekil: 'tas', ad: 'Buz' },
                      { x: 640, y: 160, r: 88, sekil: 'bulut', ad: 'Kar yığını' },
                      { x: 700, y: 360, r: 78, sekil: 'tas', ad: 'Buz' } ],
          cozum: 'Fısıltı kapıya ulaştı. Kemanı elinde, parmakları donmuş.' },
        { engel: 'Üşüyen birine önce ne verilir?',
          sahne: { tip: 'istek', nesne: 'su', adet: 4, kisi: 'agustos-bocegi', dekor: ['bulut','kutu','yuva'],
            metin: 'Fısıltı içeri girdi ama her şeyi aynı anda veremeyiz. Önce hangisi lazım — battaniye mi, çorba mı, şarkı mı?' }, gorev: 'sirala',
          yonerge: 'Yardım sırasını düşünelim: önce hangisi gelmeli?',
          ogeler: [ { ad: 'Battaniye', sekil: 'yuva' }, { ad: 'Sıcak çorba', sekil: 'su' },
                    { ad: 'Kuru yatak', sekil: 'kutu' }, { ad: 'Şarkı', sekil: 'isik' } ],
          cozum: 'Önce sıcaklık, sonra yemek, sonra dinlenme. Şarkı en sona kaldı — sırası gelecek.' },
        { engel: 'Erzak şimdi bir kişi daha fazlasına yetmeli.',
          sahne: { tip: 'istek', nesne: 'tohum', adet: 6, kisi: 'agustos-bocegi', dekor: ['kutu','bulut','yuva'],
            metin: 'Ambar üç karıncaya göre dolduruldu. Şimdi dört kişiyiz. Kapıyı açmak demek payı yeniden bölmek demek.', soz: 'Bana da yer var mı?' }, gorev: 'paylas',
          yonerge: 'Erzağı dördümüze eşit bölelim — Fısıltı da artık bizden.',
          dostlar: [ { sekil: 'inek', ad: 'Kıvırcık' }, { sekil: 'tavsan', ad: 'Pençe' },
                     { sekil: 'fok', ad: 'Tomurcuk' }, { sekil: 'kus', ad: 'Fısıltı' } ],
          yem: 'tohum', yemAd: 'Erzak', adet: 12,
          cozum: 'Dördüne de eşit düştü. Kimse aç kalmadı, kimse fazlasını almadı.' },
        { engel: 'Bahara kaç gün kaldı, hesaplamak gerek.',
          sahne: { tip: 'kesif', nesne: 'tas', adet: 5, kisi: 'agustos-bocegi', dekor: ['bulut','kutu','tas'],
            metin: 'Kışın ne kadar sürdüğünü kimse tam bilmez. Kalan erzağı tartıp bahara yetip yetmeyeceğini görmeliyiz.' }, gorev: 'terazi',
          yonerge: 'Kalan erzağı bahara yetecek şekilde dengeleyelim.',
          sol: [ { sekil: 'tas', agirlik: 3 }, { sekil: 'tas', agirlik: 2 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'Hesap tuttu: erzak bahara yetiyor. Hem de Fısıltı ile birlikte.' },
        { engel: 'Fısıltı’nın şarkısı karıncaların işini kolaylaştırıyor.',
          sahne: { tip: 'gelis', nesne: 'isik', adet: 5, kisi: 'agustos-bocegi', dekor: ['yuva','bulut','isik'],
            metin: 'Fısıltı ısındı ve kemanını aldı. Karıncalar ilk kez durup dinledi — ve iş, şarkıyla birlikte daha çabuk ilerledi.', soz: 'Şimdi sıra bende!' }, gorev: 'takimyildiz',
          yonerge: 'Fısıltı notaları yıldız gibi diziyor. Hangileri parladıysa aynılarına dokun.',
          nokta: 12, yanan: 4, tur: 2, bakma: 2400,
          cozum: 'Ezgi akılda kaldı. Yuvada bütün kış çalacak bir şarkı var artık.' },
        { engel: 'Kış uzun; yuvada oyalanacak bir şey lazım.',
          sahne: { tip: 'istek', nesne: 'kalp', adet: 4, kisi: 'agustos-bocegi', dekor: ['yuva','bulut','kutu'],
            metin: 'Kar dinmiyor, geceler uzun. Fısıltı bir oyun biliyor: bak, gözünü kapat, ne eksildi bul.' }, gorev: 'cift',
          yonerge: 'Fısıltı bir oyun öğretti: iki kart çevir, aynıysa açık kalır. Yerlerini aklında tut.',
          cift: [ 'tohum', 'kalem', 'su', 'yuva', 'elma', 'kozalak' ],
          cozum: 'Kış geceleri kısaldı; oyun oynayarak geçti.' }
      ],
      final: { engel: 'Fısıltı ısındı, karnı doydu. Şimdi sırası.',
               sahne: { tip: 'cozuldu', nesne: 'isik', adet: 6, kisi: 'agustos-bocegi', dekor: ['yuva','bulut','isik'],
               metin: 'Battaniye sarıldı, çorba içildi, pay eşit bölündü. Fısıltı kemanını aldı ve karıncalar ilk kez durup dinledi.', soz: 'Şimdi ben size çalayım.' }, etkinlik: 'besle',
               cozum: 'Fısıltı kemanını aldı ve çalmaya başladı. Karıncalar ilk kez durup dinledi.' }
    }
  ],

  kapanis: {
    baslik: 'Kış bitti. İkisi de haklıydı.',
    metin: 'Karıncalar bütün yaz çalıştığı için ambar doluydu — hazırlık olmasa kimse kışı çıkaramazdı. Ama kapıyı açmasalar, uzun kış geceleri sessiz ve karanlık geçerdi. Fısıltı’nın şarkısı yemek değildi, yine de herkesi ısıttı.\n\nBaharda tarlaya birlikte indiler. Fısıltı da bir çuval taşıdı — ve çalışırken şarkı söyledi. O yıl iş daha çabuk bitti.',
    ders: 'Hazırlık emektir, paylaşmak dostluktur.'
  }
};
