/* MASAL 02 — KAPLUMBAĞA İLE TAVŞAN (Ezop)
   ────────────────────────────────────────
   NEDEN AÇILABİLİYOR: Fabl iki cümlelik bir yarıştır. Ama bir yarış
   demek PARKUR demek — işaretlenecek yol, geçilecek dere, aşılacak orman,
   tırmanılacak tepe. Sınıf yarışı izlemiyor; parkuru kuruyor ve Ağır'a
   eşlik ediyor. 40 dakikayı dolduran şey yarışın kendi hazırlığı.

   FİNALİ YUMUŞATTIM: Ezop'ta tavşan küçük düşer. Burada Şimşek uyanıp
   ikinci gelir, surat asmaz — Ağır'ı omzuna alır ve seneye birlikte
   koşmaya karar verirler. Ders korunur: hız tek başına yetmez.
   Şimşek'in hızı da değersizleşmez; sadece süreklilik olmadan işe yaramaz. */

export default {
  kod: 'tavsan',
  ad: 'Kaplumbağa ile Tavşan',
  kaynak: 'Ezop fablı',
  ders: 'Yavaş da olsa durmadan giden, yolu bitirir',
  sure: '40 dakika · bütün sınıf',
  ozet: 'Bir yarış parkurunu baştan sona kurar, Ağır’a eşlik eder ve bitiş çizgisine birlikte varırsınız.',
  renk: '#6FA86C',
  ikon: 'kaplumbaga',

  /* KURGU: yarış. Halka yok, armağan toplama yok — iki yarışçı ve bir pist.
     Sınıfın çözdüğü her görev Ağır'ı bir adım ilerletir; Şimşek kendi
     takvimiyle koşar, uyuyakalır ve sonda uyanır. */
  kurgu: 'yaris',
  yaris: {
    bizim: { kod: 'kaplumbaga-agir', ad: 'Ağır', renk: 0x6ba15f, bas: 0xc9b781 },
    rakip: { kod: 'tavsan-simsek', ad: 'Şimşek', renk: 0xebdcc0, bas: 0xfdf6e6 }
  },

  /* Mekân: dört bölgeli bir arazi ama yol halka değil, baştan sona bir PİST.
     Bitiş çizgisi pistin ucunda; ortada seyirci tribünü var. */
  dunya: { mekan: 'parkur', yerlesim: 'pist', gok: 0xd7e8e4, cevre: 0x8fb877,
    piyon: 0x7fae5e, piyonBas: 0xa9cc7c,          // yarışı izlemeye gelen bir çayır çekirgesi
    /* Çözülen her durak parkura bir işaret bayrağı diker — yol gözle
       görülür biçimde uzuyor. */
    izNotu: { bos: 'Parkur henüz işaretsiz', dolu: '{n} işaret dikildi · yol uzuyor' },
    iz: 'bayrak', izRenk: 0xd9714f, kesifRenk: 0x5ea8b2,
    kesif: [
      { x: 8.4, z: -4.4, ikon: 'kutu', ad: 'Köprü',
        metin: 'Bu köprüyü geçen yıl bir fırtına almıştı. Bıdık bütün yaz tek başına onardı — tahtaları taşırken kabuğunda taşıdığı için kimse yardım edemedi.' },
      { x: 6.4, z: 4.6, ikon: 'kozalak', ad: 'Şimşek’in kütüğü',
        metin: 'Ormandaki en gölgeli yer. Şimşek her yarışta tam burada durup “bir dakika dinlenirim” der. Kütüğün üstünde onun yattığı yer belli oluyor.' },
      { x: 0, z: 3.4, ikon: 'yildiz', ad: 'Tribün',
        metin: 'Çayırın bütün sakinleri yarışı buradan izler. En öndeki sıra hep en küçüklere ayrılır — kural değil, gelenek.' },
      { x: -7.2, z: 6.4, ikon: 'tas', ad: 'Tepe',
        metin: 'Zirveden bütün parkur görünür: çayır, dere, orman. Ağır buraya her çıktığında bir kez durup arkasına bakar, geldiği yolu görmek için.' },
      { x: -8.6, z: -7, ikon: 'yaprak', ad: 'Çayır çiçekleri',
        metin: 'Bu çiçekler yalnızca yarış sabahı açar. Tüy bunu fark edeli üç yıl olmuş; artık yarış gününü çiçeklere bakarak ilan ediyor.' }
    ]},

  acilis: [
    { tag: 'BİR VARMIŞ, BİR YOKMUŞ', baslik: 'Çayırda bir yarış ilan edildi.', ikon: 'yildiz',
      metin: 'Tüy adında küçük bir kuş çayırın ortasına kondu ve haberi duyurdu: yarın çayırdan tepenin zirvesine bir yarış var. Yol dereden, ormandan ve dik bir yokuştan geçiyor. Katılmak isteyen sabah burada olsun.' },
    { tag: 'İKİ YARIŞMACI', baslik: 'Biri çok hızlı, biri çok yavaş.', ikon: 'kaplumbaga',
      metin: 'Sabah iki kişi geldi: Şimşek ve Ağır. Şimşek o kadar hızlıydı ki çayırı bir solukta geçiyordu. Ağır ise bir adım atıp duruyor, sonra bir adım daha atıyordu. Herkes sonucu bildiğini sandı.' },
    { tag: 'BU MASALIN KAHRAMANI SİZSİNİZ', baslik: 'Parkuru biz kuracağız.', ikon: 'yuva',
      metin: 'Ama ortada bir sorun var: parkur hazır değil. İşaretler dikilmemiş, köprü kırık, patika kapalı, yokuş taşlı. Sırayla tahtaya gelip yolu açacağız. Sonunda kimin vardığını değil, kimin hiç durmadığını göreceğiz.' }
  ],

  bolumler: [
    {
      kod: 'cayir', etapSonu: 'Çayır geçildi — yarış başladı!', ad: 'Çayır', baslik: 'Parkuru hazırla',
      renk: '#8CB963', acik: '#DDEFC4', gok: '#EAF6E0', zemin: '#A8C974',
      hikaye: 'Yarış çayırdan başlıyor. Ama işaretler yok, çöp var, bayraklar karışık. Koşu başlamadan önce yolun belli olması gerek — yoksa yarışmacılar nereye gideceğini bilemez.',
      soz: '“İyi bir yarış, iyi bir başlangıç çizgisiyle başlar.”',
      karakter: { kod: 'kus-tuy', ad: 'Tüy', tur: 'Müjdeci kuş' },
      sozler: [ 'Ben Tüy! Parkuru birlikte hazırlayalım mı?', 'Çok güzel gidiyor, yol belli oluyor!', 'Başlangıç hazır. Yarış başlayabilir!' ],
      armagan: { kod: 'bayrak', ad: 'Başlangıç bayrağı', renk: '#D9714F' },
      engeller: [
        { engel: 'Parkurun işaret direkleri dikilmemiş.',
          sahne: { tip: 'sorun', nesne: 'kazik3', adet: 5, kisi: 'kus-tuy', dekor: ['ot','fidan','yaprak'],
            metin: 'Tüy parkurun üstünde bir tur uçtu ve şaşırdı: işaret direkleri yerde yatıyor. Yol nereden başlıyor, nereye gidiyor, hiç belli değil.', soz: 'Böyle herkes kaybolur!' }, gorev: 'say',
          yonerge: 'Yolun belli olması için işaretleri birlikte dikelim.',
          sayi: 5, sekil: 'kazik3', cozum: 'Yol işaretlendi; artık kimse kaybolmaz.' },
        { engel: 'Çayıra çöp atılmış, koşarken takılırlar.',
          sahne: { tip: 'kesif', nesne: 'poset', adet: 4, kisi: 'kus-tuy', dekor: ['ot','yaprak','fidan'],
            metin: 'Tüy alçaktan uçup otların arasına baktı. Yaprakların yanına şişeler, poşetler karışmış; koşan biri bunlara takılabilir.', soz: 'Çayır bunları sevmez.' }, gorev: 'ayir',
          yonerge: 'Parkuru birlikte temizleyelim mi? Çöpü ayıralım.',
          kutular: ['Çayıra ait', 'Çöp kutusuna'],
          ogeler: [ { ad: 'Yaprak', sekil: 'yaprak', dogru: 0 }, { ad: 'Çiçekli ot', sekil: 'ot', dogru: 0 },
                    { ad: 'Taş', sekil: 'tas', dogru: 0 }, { ad: 'Şişe', sekil: 'sise', dogru: 1 },
                    { ad: 'Poşet', sekil: 'poset', dogru: 1 }, { ad: 'Ayakkabı', sekil: 'ayakkabi', dogru: 1 } ],
          cozum: 'Çayır tertemiz; kimse çöpe takılmayacak.' },
        { engel: 'Seyirciler bayrak dalgası yapıyor.',
          sahne: { tip: 'gelis', nesne: 'bayrak', adet: 6, kisi: 'kus-tuy', dekor: ['bayrak','ot','fidan'],
            metin: 'Tribün doldu, herkes elinde bir bayrakla geldi. Tüy kocaman bir dalga yapmak istiyor ama bayraklar karışık kalkıyor.', soz: 'Sırayla kaldıralım, olur mu?' }, gorev: 'takimyildiz',
          yonerge: 'Seyirciler bayrakları sırayla kaldırıyor. Hangileri parladıysa aynılarına dokun.',
          nokta: 12, yanan: 4, tur: 2, bakma: 2300,
          cozum: 'Dalga tamamlandı; tribün yarışa hazır.' },
        { engel: 'Başlangıç taşları otların arasında kaybolmuş.',
          sahne: { tip: 'kesif', nesne: 'tas', adet: 3, kisi: 'kus-tuy', dekor: ['ot','fidan','ot'],
            metin: 'Bir gecede otlar öyle uzamış ki başlangıç taşları görünmez olmuş. Taşların yanında saklambaç oynayan üç küçük dost da kaybolmuş.', soz: 'Neredesiniz? Sizi bulacağım!' }, gorev: 'gizli',
          yonerge: 'Otların arasına iyi bakalım — saklanan dostları bulalım.',
          tohum: 13, sus: 24, susBoy: [4, 8], boy: 12,
          gizli: [ { sekil: 'kaplumbaga', ad: 'Kaplumbağa', x: 21, y: 63, a: -8 },
                   { sekil: 'tavsan', ad: 'Tavşan', x: 75, y: 29, a: 7 },
                   { sekil: 'sincap', ad: 'Sincap', x: 48, y: 76, a: 13 } ],
          cozum: 'Üçü de bulundu; başlangıç çizgisi ortaya çıktı.' },
        { engel: 'Başlama düdüğü tam zamanında çalmalı.',
          sahne: { tip: 'istek', nesne: 'bayrak', adet: 2, kisi: 'kus-tuy', dekor: ['bayrak','ot','fidan'],
            metin: 'Ağır ile Şimşek çizginin arkasında bekliyor. Düdük erken çalarsa biri hazır olmaz, geç çalarsa herkes sabırsızlanır.', soz: 'Tam zamanında çalalım.' }, gorev: 'zaman',
          yonerge: 'Tüy çizginin üstündeyken düdüğü çalalım — acelemiz yok.',
          tasiyici: 'kus', tasiyiciAd: 'Tüy', yuk: 'yildiz',
          hedef: 'kazik3', hedefAd: 'Başlangıç çizgisi', genislik: 32, hiz: 1, hedefSayisi: 3,
          cozum: 'Düdük tam zamanında çaldı; yarış başladı!' },
        { engel: 'Yarışmacılar numaralarını kaybetmiş.',
          sahne: { tip: 'sorun', nesne: 'yildiz', adet: 6, kisi: 'kus-tuy', dekor: ['ot','bayrak','yaprak'],
            metin: 'Bir rüzgâr esti, yarışmacıların göğüs numaraları havalandı. Hepsi ters düştü; hangisi kimin, kimse bilmiyor.', soz: 'Eyvah, karıştılar!' }, gorev: 'cift',
          yonerge: 'Numaralar kapalı duruyor. İki kart çevir, aynıysa açık kalır — yerlerini aklında tut.',
          cift: [ 'kaplumbaga', 'tavsan', 'sincap', 'kus', 'yildiz', 'yaprak' ],
          cozum: 'Bütün numaralar eşleşti; herkes kendi göğsüne taktı.' }
      ],
      final: { engel: 'Tüy sabahtan beri uçup duruyor, acıkmış.',
               sahne: { tip: 'istek', nesne: 'tohum', adet: 4, kisi: 'kus-tuy', dekor: ['ot','bayrak','fidan'],
               metin: 'Direkler dikildi, çayır temizlendi, düdük çaldı. Tüy bir direğin tepesine kondu; kanatları yorgun, karnı guruldadı.', soz: 'Birkaç tohum bulabilir miyiz?' }, etkinlik: 'besle', yem: 'tohum',
               cozum: 'Tüy karnını doyurdu. “Başlangıç bayrağı sizin,” dedi ve kanadıyla selam verdi.' }
    },
    {
      kod: 'dere', etapSonu: 'Dere geçildi — karşı kıyıdayız!', ad: 'Dere', baslik: 'Karşıya geç',
      renk: '#5EA8B2', acik: '#D6EEF0', gok: '#E6F5F6', zemin: '#8FC2AE',
      hikaye: 'Parkurun ikinci etabı dereden geçiyor. Köprünün tahtaları kırılmış, sal dengesiz, nilüferler dağınık. Suyun karşısına geçmenin birden fazla yolu var — hangisini kurarsak onu kullanacağız.',
      soz: '“Acele eden suya düşer; bakıp geçen karşıya varır.”',
      karakter: { kod: 'salyangoz-bidik', ad: 'Bıdık', tur: 'Parkur görevlisi salyangoz' },
      sozler: [ 'Ben Bıdık. Acelem yok ama işimi bilirim!', 'Güzel gidiyor, karşıya yaklaşıyoruz.', 'Geçit açıldı. Bak, yavaş gitmek işe yaradı!' ],
      armagan: { kod: 'su', ad: 'Su matarası', renk: '#3FA9E0' },
      engeller: [
        { engel: 'Köprünün tahtaları kırılmış.',
          sahne: { tip: 'sorun', nesne: 'kutu', adet: 4, kisi: 'salyangoz-bidik', dekor: ['su','tas','ot'],
            metin: 'Parkur dereye vardı ama köprünün tahtaları yerinde değil. Bıdık kırık tahtaları tek tek kıyıya çekmiş, şimdi düşünüyor.', soz: 'Bunlar nasıl birleşiyordu?' }, gorev: 'yapboz',
          yonerge: 'Parçaları yerine koyup köprüyü birlikte onaralım mı?',
          resim: 'kutu', satir: 2, sutun: 2,
          cozum: 'Köprü onarıldı; tahtalar yerli yerinde.' },
        { engel: 'Sal bir yana yatıyor, yük dengesiz.',
          sahne: { tip: 'sorun', nesne: 'tas', adet: 4, kisi: 'salyangoz-bidik', dekor: ['su','kabuk','ot'],
            metin: 'Sal suya indi ama hep bir yanına yatıyor. Bir tarafta taş çok, öbür tarafta az; böyle kimse binemez.', soz: 'Önce dengeleyelim.' }, gorev: 'terazi',
          yonerge: 'Sağ kefeye taş ekleyip salı dengeleyelim. Fazla gelirse geri alırız.',
          sol: [ { sekil: 'tas', agirlik: 2 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'Sal dengelendi; artık güvenle yüzüyor.' },
        { engel: 'Dereden kütükler akıp gidiyor.',
          sahne: { tip: 'gelis', nesne: 'kazik2', adet: 5, kisi: 'salyangoz-bidik', dekor: ['su','tas','fidan'],
            metin: 'Yukarıdan dere boyunca kütükler akıp geliyor. Bıdık onlardan bir sal yapmak istiyor ama kütükler onun için çok hızlı.', soz: 'Bana yardım eder misiniz?' }, gorev: 'yakala',
          yonerge: 'Dereden kütükler akıp geliyor. Parmağını aşağıda gezdir, sala lazım olanları tut.',
          hedef: 8, hiz: .2, sikayet: 1100, iyi: [ 'kazik2', 'yaprak' ], kotu: [ 'tas' ],
          cozum: 'Kütükler toplandı; onlardan bir sal kuruldu.' },
        { engel: 'Suya ne düşerse batmaz — hangisi yüzer?',
          sahne: { tip: 'kesif', nesne: 'yaprak', adet: 5, kisi: 'salyangoz-bidik', dekor: ['su','kabuk','tas'],
            metin: 'Bıdık kıyıda bir yığın buldu: yapraklar, dallar, taşlar, kozalaklar. Sal için yüzenler lazım; ama hangileri yüzer?', soz: 'Suya atmadan bilebilir miyiz?' }, gorev: 'ayir',
          yonerge: 'Hangisi suda yüzer, hangisi batar? Birlikte deneyelim.',
          kutular: ['Suda yüzer', 'Suya batar'],
          ogeler: [ { ad: 'Yaprak', sekil: 'yaprak', dogru: 0 }, { ad: 'Dal', sekil: 'kazik2', dogru: 0 },
                    { ad: 'Kabuk', sekil: 'kabuk', dogru: 0 }, { ad: 'Taş', sekil: 'tas', dogru: 1 },
                    { ad: 'Palamut', sekil: 'palamut', dogru: 1 }, { ad: 'Kozalak', sekil: 'kozalak', dogru: 1 } ],
          cozum: 'Yüzenlerden bir sal oldu; batanlar kıyıda kaldı.' },
        { engel: 'Mataralar boş, yolun yarısı daha var.',
          sahne: { tip: 'istek', nesne: 'su', adet: 5, kisi: 'salyangoz-bidik', dekor: ['su','ot','fidan'],
            metin: 'Güneş yükseldi, herkesin matarası boşaldı. Dereden temiz su doldurduk; birine çok, birine az giderse yolda susayan olur.', soz: 'Eşit bölelim.' }, gorev: 'paylas',
          yonerge: 'Suyu üç yarışmacıya eşit paylaştıralım mı?',
          dostlar: [ { sekil: 'kaplumbaga', ad: 'Ağır' }, { sekil: 'tavsan', ad: 'Şimşek' }, { sekil: 'sincap', ad: 'Fındık' } ],
          yem: 'su', yemAd: 'Su', adet: 9,
          cozum: 'Üçünün de matarası eşit doldu.' },
        { engel: 'Derenin üstünden geçen ince bir yol var.',
          sahne: { tip: 'gelis', nesne: 'su', adet: 3, kisi: 'salyangoz-bidik', dekor: ['su','tas','kabuk'],
            metin: 'Derenin ortasında taşlardan ince bir yol var. Aralarda küçük girdaplar dönüyor; Bıdık yavaş gider ama dikkatli gitmeli.', soz: 'Acelem yok, yolu gösterin yeter.' }, gorev: 'yol',
          yonerge: 'Girdaplara değmeden Bıdık’ı karşı kıyıya götürelim.',
          baslangic: { x: 105, y: 220, sekil: 'salyangoz-bidik', ad: 'Bıdık' },
          bitis: { x: 900, y: 220, sekil: 'yildiz', ad: 'Karşı kıyı' },
          engeller: [ { x: 400, y: 130, r: 88, sekil: 'su', ad: 'Girdap' },
                      { x: 620, y: 320, r: 88, sekil: 'su', ad: 'Girdap' } ],
          cozum: 'Bıdık karşıya geçti; iz bıraktığı yoldan diğerleri de geçecek.' }
      ],
      final: { engel: 'Bıdık bütün gün suyun kenarında çalıştı.',
               sahne: { tip: 'cozuldu', nesne: 'kutu', adet: 4, kisi: 'salyangoz-bidik', dekor: ['su','kabuk','fidan'],
               metin: 'Köprü onarıldı, sal yüzüyor, herkes karşı kıyıda. Bıdık kabuğuna yaslanmış; yorgun ama çok mutlu.', soz: 'Biraz sevilmek iyi gelirdi.' }, etkinlik: 'sev',
               cozum: 'Bıdık kabuğundan başını çıkardı. “Su matarası sizin,” dedi. “Yolun yarısı bitti.”' }
    },
    {
      kod: 'orman', etapSonu: 'Orman geçildi — Şimşek hâlâ uyuyor!', ad: 'Orman', baslik: 'Patikayı aç',
      renk: '#5F9E5F', acik: '#D8EDCB', gok: '#E9F4E2', zemin: '#7EA86A',
      hikaye: 'Üçüncü etap ormandan geçiyor. Şimşek çoktan buraya vardı; o kadar öndeydi ki bir kütüğün gölgesinde uzanıp gözlerini kapattı. “Nasılsa yetişirim,” dedi. Ağır ise hâlâ geliyor — durmadan.',
      soz: '“Durmak da bir seçimdir; her adım gibi.”',
      karakter: { kod: 'tavsan-simsek', ad: 'Şimşek', tur: 'Yarışçı tavşan' },
      sozler: [ 'Ben Şimşek! Bir dakika dinlenirim, nasılsa yetişirim.', 'Hı? Ne kadar uyumuşum…', 'Anladım: hızlı olmak yetmiyormuş.' ],
      armagan: { kod: 'yaprak', ad: 'Gölge yaprağı', renk: '#5F9E5F' },
      engeller: [
        { engel: 'Patikaya dallar düşmüş.',
          sahne: { tip: 'sorun', nesne: 'dal3', adet: 4, kisi: 'kaplumbaga-agir', dekor: ['agac','kozalak','yaprak'],
            metin: 'Gece esen rüzgâr ormanda dalları kırmış, hepsi patikanın üstüne düşmüş. Ağır adım adım yaklaşıyor ama bu dallardan geçemez.', soz: 'Kenara dizersek geçerim.' }, gorev: 'sirala',
          yonerge: 'Patikayı açalım — dalları kısadan uzuna dizelim.',
          ogeler: [ { ad: 'En kısa', sekil: 'dal1' }, { ad: 'Kısa', sekil: 'dal2' },
                    { ad: 'Uzun', sekil: 'dal3' }, { ad: 'En uzun', sekil: 'dal4' } ],
          cozum: 'Patika açıldı; dallar kenara istiflendi.' },
        { engel: 'Şimşek’in çantasından bir şey eksiliyor.',
          sahne: { tip: 'kesif', nesne: 'elma', adet: 4, kisi: 'tavsan-simsek', dekor: ['agac','yaprak','kozalak'],
            metin: 'Şimşek kütüğün dibinde çantasını açtı: matara, elma, fırça… Esneyip gözlerini kırptı, bir daha baktı. Bir şey eksik gibi.', soz: 'Hı? Az önce buradaydı…' }, gorev: 'kayip',
          yonerge: 'Çantaya iyi bakalım. Gözümüzü kapayıp açınca ne eksildi, bulalım.',
          tur: 2,
          ogeler: [ { ad: 'Mataraa', sekil: 'sise' }, { ad: 'Elma', sekil: 'elma' },
                    { ad: 'Yaprak', sekil: 'yaprak' }, { ad: 'Kozalak', sekil: 'kozalak' },
                    { ad: 'Fırça', sekil: 'firca' } ],
          cozum: 'Eksilen bulundu; çanta yeniden tamam.' },
        { engel: 'Ormana ait olmayan bir şey karışmış.',
          sahne: { tip: 'sorun', nesne: 'sise', adet: 4, kisi: 'tavsan-simsek', dekor: ['agac','kozalak','fidan'],
            metin: 'Patikada kozalakların arasına şişeler, taşlar, kabuklar karışmış. Koşan biri bunlara basıp tökezleyebilir.', soz: 'Bunlar ormanın değil!' }, gorev: 'refleks',
          yonerge: 'Koşarken karar vermek gerek. Yalnızca kozalağa dokun; başkası gelirse elini çek.',
          hedef: 8, gorunme: 1050, ara: 320,
          aranan: { sekil: 'kozalak', ad: 'Kozalak' },
          digerleri: [ { sekil: 'sise', ad: 'Şişe' }, { sekil: 'tas', ad: 'Taş' }, { sekil: 'kabuk', ad: 'Kabuk' } ],
          cozum: 'Patika temizlendi; koşarken hiçbir şeye takılmayacağız.' },
        { engel: 'Orman dostları sırayla seslendi.',
          sahne: { tip: 'gelis', nesne: 'kus', adet: 4, kisi: 'tavsan-simsek', dekor: ['agac','yaprak','kozalak'],
            metin: 'Orman dostları Şimşek’i uyandırmak için sırayla seslendi: önce biri, sonra öbürü. Şimşek uykulu kulaklarını dikti ama sırayı kaçırdı.', soz: 'Bir daha seslenin, dinliyorum!' }, gorev: 'dizi',
          yonerge: 'Önce dinleyelim, sonra aynı sırayla dokunalım. Acelemiz yok.',
          dostlar: [ { sekil: 'inek', ad: 'Boncuk' }, { sekil: 'tavsan', ad: 'Şimşek' },
                     { sekil: 'fok', ad: 'Bıdık' }, { sekil: 'kus', ad: 'Tüy' } ],
          uzunluklar: [ 2, 3, 4 ],
          cozum: 'Sıra doğru hatırlandı; orman yankılandı.' },
        { engel: 'Yavrular annelerini kaybetmiş.',
          sahne: { tip: 'istek', nesne: 'yuva', adet: 4, kisi: 'tavsan-simsek', dekor: ['agac','yaprak','fidan'],
            metin: 'Yavrular oyuna dalıp yuvalarından uzaklaşmış. Anneleri de onları arıyor; yalnızca biraz yol göstermek gerek.', soz: 'Hadi, herkesi annesine götürelim.' }, gorev: 'eslestir',
          yonerge: 'Yavruları annelerine kavuşturmama yardım eder misin?',
          ciftler: [ { a: 'Sincap yavrusu', asekil: 'palamut', b: 'Sincap', bsekil: 'sincap' },
                     { a: 'Baykuş yavrusu', asekil: 'yumurta', b: 'Baykuş', bsekil: 'baykus' },
                     { a: 'Tavşan yavrusu', asekil: 'ot', b: 'Tavşan', bsekil: 'tavsan' },
                     { a: 'Kuş yavrusu', asekil: 'yuva', b: 'Kuş', bsekil: 'kus' } ],
          cozum: 'Herkes annesini buldu; orman sakinleşti.' },
        { engel: 'Gölgede dinlenecek yer bir düzende hazırlanmalı.',
          sahne: { tip: 'kesif', nesne: 'yaprak', adet: 6, kisi: 'tavsan-simsek', dekor: ['agac','kozalak','yaprak'],
            metin: 'Kütüğün yanında yapraklarla kozalaklar sırayla dizilmiş. Ama dizinin ortası dağılmış; gölgelik yarım kalmış.', soz: 'Sıra neydi, hatırlıyor musunuz?' }, gorev: 'oruntu',
          yonerge: 'Şeridi baştan okuyalım. Boşluğa hangisi geliyor?',
          dizi: [ 'yaprak', 'kozalak', 'yaprak', 'kozalak', null, null, 'yaprak' ],
          cevaplar: [ 'yaprak', 'kozalak' ],
          secenekler: [ { sekil: 'yaprak', ad: 'Yaprak' }, { sekil: 'kozalak', ad: 'Kozalak' }, { sekil: 'palamut', ad: 'Palamut' } ],
          cozum: 'Gölgelik hazır; yorulan burada dinlenebilir.' }
      ],
      final: { engel: 'Şimşek uyandı, tüyleri karmakarışık.',
               sahne: { tip: 'gelis', nesne: 'yaprak', adet: 5, kisi: 'tavsan-simsek', dekor: ['agac','yaprak','kozalak'],
               metin: 'Şimşek gerinip gözlerini açtı. Kulakları yaprak dolu, tüyleri darmadağın; üstelik Ağır çoktan ormandan çıkmış!', soz: 'Ne kadar uyumuşum… Önce bir toparlanayım.' }, etkinlik: 'timarla',
               cozum: 'Şimşek toparlandı. “Gölge yaprağı sizin,” dedi. “Ben de artık koşacağım — ama bu sefer durmadan.”' }
    },
    {
      kod: 'tepe', etapSonu: 'Zirve göründü!', ad: 'Tepe', baslik: 'Son yokuş',
      renk: '#C9A05A', acik: '#F3E6C6', gok: '#F7EFDC', zemin: '#C3C49A',
      hikaye: 'Son etap dik bir yokuş. Ağır buraya geldiğinde güneş batmak üzereydi ve hiç durmamıştı. Şimşek arkadan koşuyor. Yokuş taşlı, yük ağır, su az. Ama zirve göründü.',
      soz: '“Zirve, en hızlıyı değil, en sürekliyi bekler.”',
      karakter: { kod: 'kaplumbaga-agir', ad: 'Ağır', tur: 'Yarışçı kaplumbağa' },
      sozler: [ 'Ben Ağır. Hızlı değilim ama durmam.', 'Bir adım daha… bir adım daha…', 'Vardım! Hiç durmadım ve vardım.' ],
      armagan: { kod: 'celenk', ad: 'Zafer çelengi', renk: '#D8A34F' },
      engeller: [
        { engel: 'Yokuşu kayan taşlar kapatmış.',
          sahne: { tip: 'sorun', nesne: 'kaya3', adet: 5, kisi: 'kaplumbaga-agir', dekor: ['tas','fidan','ot'],
            metin: 'Yokuşun başında taşlar kaymış, yolun ortasına yığılmış. Ağır yavaş ama kararlı: aralarından geçen bir yol mutlaka vardır.', soz: 'Yolu gösterin, gerisini ben yürürüm.' }, gorev: 'yol',
          yonerge: 'Kayalara değmeden Ağır’a zirveye giden bir yol çizelim.',
          baslangic: { x: 100, y: 220, sekil: 'kaplumbaga-agir', ad: 'Ağır' },
          bitis: { x: 905, y: 220, sekil: 'celenk', ad: 'Zirve' },
          engeller: [ { x: 330, y: 120, r: 86, sekil: 'tas', ad: 'Kaya' },
                      { x: 420, y: 330, r: 82, sekil: 'tas', ad: 'Kaya' },
                      { x: 640, y: 160, r: 88, sekil: 'tas', ad: 'Kaya' },
                      { x: 700, y: 360, r: 78, sekil: 'tas', ad: 'Kaya' } ],
          cozum: 'Yol bulundu; Ağır tırmanmaya devam ediyor.' },
        { engel: 'Ağır’ın sırtındaki yük bir yana kaymış.',
          sahne: { tip: 'sorun', nesne: 'tas', adet: 3, kisi: 'kaplumbaga-agir', dekor: ['tas','ot','fidan'],
            metin: 'Ağır’ın sırtındaki heybe bir yana kaymış. Bir yanı ağır, bir yanı hafif; her adımda yan yatıyor.', soz: 'Böyle yürümek çok zor.' }, gorev: 'terazi',
          yonerge: 'İki yanı eşitleyelim ki taşımak kolay olsun.',
          sol: [ { sekil: 'tas', agirlik: 3 }, { sekil: 'tas', agirlik: 2 } ],
          havuz: [ { ad: 'Küçük', agirlik: 1 }, { ad: 'Küçük', agirlik: 1 }, { ad: 'Orta', agirlik: 2 },
                   { ad: 'Orta', agirlik: 2 }, { ad: 'Büyük', agirlik: 3 } ],
          cozum: 'Yük dengelendi; sırt artık ağrımıyor.' },
        { engel: 'Zirveye giden basamaklar bir düzende dizilecek.',
          sahne: { tip: 'gelis', nesne: 'kutu', adet: 5, kisi: 'kaplumbaga-agir', dekor: ['tas','fidan','ot'],
            metin: 'Yokuşun en dik yerinde basamaklar var: bir taş, bir tahta, bir taş… Ama aradakiler yerinden çıkmış.', soz: 'Sırayı bulursak tırmanırım.' }, gorev: 'oruntu',
          yonerge: 'Şeridi baştan okuyalım: sonra hangisi geliyor?',
          dizi: [ 'tas', 'kutu', 'tas', 'kutu', null, null, 'tas' ],
          cevaplar: [ 'tas', 'kutu' ],
          secenekler: [ { sekil: 'tas', ad: 'Taş basamak' }, { sekil: 'kutu', ad: 'Tahta basamak' }, { sekil: 'kozalak', ad: 'Kozalak' } ],
          cozum: 'Basamaklar düzene girdi; tırmanmak kolaylaştı.' },
        { engel: 'Kalan su herkese yetmeli.',
          sahne: { tip: 'istek', nesne: 'su', adet: 4, kisi: 'kaplumbaga-agir', dekor: ['tas','ot','fidan'],
            metin: 'Yokuşun yarısında kısa bir soluk. Matarada az su kaldı; tam o sırada Şimşek de nefes nefese yetişti.', soz: 'Şimşek de susamış. Paylaşalım.' }, gorev: 'paylas',
          yonerge: 'Kalan suyu dördümüze eşit bölelim — Şimşek de susadı.',
          dostlar: [ { sekil: 'kaplumbaga', ad: 'Ağır' }, { sekil: 'tavsan', ad: 'Şimşek' },
                     { sekil: 'sincap', ad: 'Fındık' }, { sekil: 'kus', ad: 'Tüy' } ],
          yem: 'su', yemAd: 'Su', adet: 12,
          cozum: 'Dördüne de eşit düştü; kimse susuz kalmadı.' },
        { engel: 'Zafer çelengi düşüp parçalanmış.',
          sahne: { tip: 'sorun', nesne: 'celenk', adet: 3, kisi: 'kaplumbaga-agir', dekor: ['tas','fidan','ot'],
            metin: 'Zirvedeki çelenk rüzgârda devrilip yokuştan yuvarlanmış. Yaprakları bir yana, çiçekleri bir yana dağılmış.', soz: 'Onu birlikte toplayalım.' }, gorev: 'yapboz',
          yonerge: 'Parçaları yerine koyup çelengi birlikte tamamlayalım.',
          resim: 'celenk', satir: 2, sutun: 2,
          cozum: 'Çelenk yeniden bütün; zirvede bekliyor.' },
        { engel: 'Ağır son yokuşta, yanında biri olmalı.',
          sahne: { tip: 'istek', nesne: 'yildiz', adet: 3, kisi: 'kaplumbaga-agir', dekor: ['tas','ot','fidan'],
            metin: 'Zirve göründü. Güneş batıyor, Ağır’ın bacakları yoruldu ama durmuyor. Yanında biri olursa son adımlar kolaylaşır.', soz: 'Benimle gelir misiniz?' }, gorev: 'takip',
          yonerge: 'Ağır yavaş ama durmadan tırmanıyor. Parmağını üstüne koy ve kaldırmadan zirveye kadar götür.',
          sekil: 'kaplumbaga-agir', sure: 6000, hiz: .6, boy: 16,
          cozum: 'Ağır hiç durmadan tırmandı — ve zirveye vardı.' }
      ],
      final: { engel: 'Ağır zirveye vardı — yorgun ama hiç durmamış.',
               sahne: { tip: 'cozuldu', nesne: 'yildiz', adet: 5, kisi: 'kaplumbaga-agir', dekor: ['tas','fidan','ot'],
               metin: 'Ağır son adımı attı ve çelengin yanına vardı. Bütün gün bir kez bile durmadı; şimdi karnı aç, gözleri parlıyor.', soz: 'Vardım! Biraz yiyebilir miyim?' }, etkinlik: 'besle',
               cozum: 'Ağır karnını doyurdu ve başını kaldırdı. Tam o sırada Şimşek de zirveye çıktı.' }
    }
  ],

  kapanis: {
    baslik: 'Ağır vardı. Şimşek de öğrendi.',
    metin: 'Ağır zirveye ilk vardı. Hızlı olduğu için değil — bir kez bile durmadığı için. Attığı her adım küçüktü ama hepsi ileriye doğruydu.\n\nŞimşek arkadan geldi, nefes nefese. Surat asmadı, bahane de uydurmadı. Ağır’ın yanına gidip onu omzuna aldı ve zirvede birlikte döndüler. “Seneye,” dedi Şimşek, “birlikte koşalım. Sen bana durmamayı öğret, ben sana hızlanmayı.”\n\nO günden sonra çayırda her yarışı ikisi birlikte açtı.',
    ders: 'Yavaş da olsa durmadan giden, yolu bitirir.'
  }
};
